### ISSUE TITLE
Step 2 - correction

### ISSUE THREAD

**Issue by HenrikMPedersen** [MicrosoftDocs/MIMDocs#103]
import-module activedirectory
$sp = ConvertTo-SecureString "Pass1Word" –asplaintext –force
New-ADUser –SamAccountName MIMINSTALL –name MIMINSTALL
Set-ADAccountPassword –identity MIMINSTALL –NewPassword $sp
Set-ADUser –identity MIMINSTALL –Enabled 1 –PasswordNeverExpires 1
New-ADUser –SamAccountName MIMMA –name MIMMA
Set-ADAccountPassword –identity MIMMA –NewPassword $sp
Set-ADUser –identity MIMMA –Enabled 1 –PasswordNeverExpires 1
New-ADUser –SamAccountName MIMSync –name MIMSync
Set-ADAccountPassword –identity MIMSync –NewPassword $sp
Set-ADUser –identity MIMSync –Enabled 1 –PasswordNeverExpires 1
New-ADUser –SamAccountName MIMService –name MIMService
Set-ADAccountPassword –identity MIMService –NewPassword $sp
Set-ADUser –identity MIMService –Enabled 1 –PasswordNeverExpires 1
New-ADUser –SamAccountName MIMSSPR –name MIMSSPR
Set-ADAccountPassword –identity MIMSSPR –NewPassword $sp
Set-ADUser –identity MIMSSPR –Enabled 1 –PasswordNeverExpires 1
New-ADUser –SamAccountName SharePoint –name SharePoint
Set-ADAccountPassword –identity SharePoint –NewPassword $sp
Set-ADUser –identity SharePoint –Enabled 1 –PasswordNeverExpires 1
New-ADUser –SamAccountName SqlServer –name SqlServer
Set-ADAccountPassword –identity SqlServer –NewPassword $sp
Set-ADUser –identity SqlServer –Enabled 1 –PasswordNeverExpires 1
New-ADUser –SamAccountName BackupAdmin –name BackupAdmin
Set-ADAccountPassword –identity BackupAdmin –NewPassword $sp
Set-ADUser –identity BackupAdmin –Enabled 1 -PasswordNeverExpires 1
New-ADUser –SamAccountName MIMpool –name MIMpool
Set-ADAccountPassword –identity MIMPool –NewPassword $sp
Set-ADUser –identity MIMPool –Enabled 1 -PasswordNeverExpires 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [Set up a domain for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain#feedback)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **barclayn**

**Comment by billmath** [comment]
@HenrikMPedersen can you please clarify this.  I am not really sure what the issue is.  Thanks!

**Comment by billmath** [comment]
I have not heard back.
#please-close

**Comment by HenrikMPedersen** [comment]
Hi Bill.

 

I have been on two weeks vacation. I will get back to You during this coming week.

 

Br,

HP

**Comment by kcobbva** [comment]
@Bill   It looks like the add was due to misconfiguration in the script.   e.g.:  
New-ADUser –SamAccountName MIMINSTALL –name MIMMA

was replaced with:

New-ADUser –SamAccountName MIMINSTALL –name MIMINSTALL

there are a few others like that in the script that's been updated as well.

**Comment by ioamnesia** [comment]
Yeah, MIMPool is the wrong as well!

**Comment by ioamnesia** [comment]
Just save space and grief:

import-module activedirectory
$sp = ConvertTo-SecureString "Pass@word1" –asplaintext –force
$users = @("MIMINSTALL", "MIMMA", "MIMSync", "MIMService","MIMSSPR","SharePoint","SqlServer","BackupAdmin","MIMpool")
$users | % {
New-ADUser –SamAccountName $_ –name $_
 Set-ADAccountPassword –identity $_–NewPassword $sp
 Set-ADUser –identity $_–Enabled 1 –PasswordNeverExpires 1
}

**Comment by yongchin83** [comment]
@ioamnesia correction as there are missing syntax after copy and paste

import-module activedirectory
$sp = ConvertTo-SecureString "Pass@word1" –asplaintext –force
$users = @("MIMINSTALL", "MIMMA", "MIMSync", "MIMService","MIMSSPR","SharePoint","SqlServer","BackupAdmin","MIMpool")
$users | % {
New-ADUser –SamAccountName $_ –name $_
Set-ADAccountPassword –identity $_ –NewPassword $sp
Set-ADUser –identity $_ –Enabled 1 –PasswordNeverExpires 1
}

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
