### ISSUE TITLE
Hotfix link not inlcuded

### ISSUE THREAD

**Issue by andrewjsilcock** [MicrosoftDocs/MIMDocs#106]
At the top of the article the following needs updating "Hotfix Required: &lt;link to latest KB&gt;", assuming it should be linked to https://support.microsoft.com/en-us/help/4073679

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56576f6a-6c24-404b-1b11-d2fc144eeea7
* Version Independent ID: 033bd935-3104-258e-e3ba-8161603c08e7
* Content: [Conversion of MIM Specific Services to gMSA](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-gmsa)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-gmsa.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-gmsa.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @fimguy
* Microsoft Alias: **billmath**

**Comment by fimguy** [comment]
Agree / now that the KB is public will update

**Comment by markwahl-msft** [comment]
#please-close
