### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by DLundell** [MicrosoftDocs/MIMDocs#108]
The link to the "Generic SQL Connector for FIM 2010 R2 / MIM" actually goes to the generic LDAP MA. The Link for the Generic LDAP MA is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 283b877c-23f3-160f-1477-4fc0f4af656a
* Version Independent ID: 98e4df41-4636-b0a4-93b8-8c89b94c4949
* Content: [Supported connectors](https://docs.microsoft.com/en-us/microsoft-identity-manager/supported-management-agents#feedback)
* Content Source: [MIMDocs/supported-management-agents.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/supported-management-agents.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @fimguy
* Microsoft Alias: **fimguy**

**Comment by markwahl-msft** [comment]
Resolved
