### ISSUE TITLE
Confusing PAM-AD PIM-AAD

### ISSUE THREAD

**Issue by BZanten** [MicrosoftDocs/MIMDocs#109]
This document is very nice overall, but it confuses me in some ways.
In the first alineas PAM is depicted as a security solutions for AD (so: onprem) but then states: PAM is an instance of PIM that is implemented using MIM. If I follow the link to PIM, PIM seems to focus on Azure AD (AAD) not AD...

secondly: in the alinea: "How does PAM work?" just before the picture it says: "The following example shows how PIM works in more detail." so shouldn't that read: The following example shows how PAM works in more detail.  (?)

So overal when I'm interested in securing our on premise AD, I'm a little confuse on the usage of PAM, or both PAM and PIM, and whether PIM only managed AAD or both AAD and AD.

Regards, Ben van Zanten

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f97232d5-629b-3ac3-7b67-4af90e70c551
* Version Independent ID: e2c1c9d6-8b91-5dee-3240-668e4c3158a4
* Content: [Privileged Access Management for Active Directory Domain Services](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/privileged-identity-management-for-active-directory-domain-services)
* Content Source: [MIMDocs/pam/privileged-identity-management-for-active-directory-domain-services.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/privileged-identity-management-for-active-directory-domain-services.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by barclayn** [comment]
@BZanten PAM is for management of on-premises resources. PIM is for cloud... from https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-configure 
 "With Azure Active Directory (Azure AD) Privileged Identity Management, you can manage, control, and monitor access within your organization. This includes access to resources in Azure AD, Azure resources, and other Microsoft Online Services like Office 365 or Microsoft Intune."

**Comment by pritidhara** [comment]
I have a similar confusion as BZanten. So as per the clarification, PIM , which comes with EMS 5 is used for managing Azure Ad roles Azure resource roles. It cannot be used to manage privilege access for other platforms or non-Azure based applications.

PAM is a different product that is used for managing privilege access in on-prem AD. It does not come with EMS 5.

Is this understanding correct?

**Comment by uowdaniel** [comment]
I think "The following example shows how PIM works in more detail." is a typo or copy/paste error and should read "The following example shows how PAM works in more detail."

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close

**Comment by BZanten** [comment]
Well, so that is what collaboration looks like. I raise an issue where I kind of already exactly describe what is the problem. looking at the other reaction my issue is not nonsense..  then nothing is done with it for years, then it is closed 'because nothing is done' with it... why isn't it closed because the text is simply updated.  This does NOT give me the idea my contribution is valuable in any way.
