### ISSUE TITLE
Connector Samples are Woefully Lacking

### ISSUE THREAD

**Issue by ioamnesia** [MicrosoftDocs/MIMDocs#110]
The sample connectors provided do not cover topics like Partition & Hierarchy Discovery or the Password Synchronization. Sample Connectors contain a number of bugs. Failure to cover distinguished name configurations (Samples only use "None" distinguished name type). I spent hours dealing with "DN is unavailable" errors caused by including a DN column in the schema. Renaming the column to "mydn" fixed my issues, so there is a conflict if an injested csentry has an attributeentry named "dn". Arg!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b54e1b-514a-d354-0f14-10194f64b08a
* Version Independent ID: 4b9bcb87-3197-4ef4-672a-68daf5022078
* Content: [PowerShell Connector](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/microsoft-identity-manager-2016-connector-powershell)
* Content Source: [MIMDocs/reference/microsoft-identity-manager-2016-connector-powershell.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/microsoft-identity-manager-2016-connector-powershell.md)
* Service: **active-directory**
* GitHub Login: @billmath
* Microsoft Alias: **davidste**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
