### ISSUE TITLE
Missing Example

### ISSUE THREAD

**Issue by mliben** [MicrosoftDocs/MIMDocs#111]
Text for RightsLevel indicates there is an example; however, no example is visible.

"This example shows how a RightsLevel attribute can be used with a data source. If you have used the template for a data source shown earlier in this document, your data source is rights. Use the attribute name as the Path."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1584e6a9-c3cc-d7b7-2703-53e43814b5da
* Version Independent ID: ee693503-56e7-1ce2-648e-385be0eabb4e
* Content: [Resource control display configuration XML reference](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/rcd-configuration-xml-reference)
* Content Source: [MIMDocs/reference/rcd-configuration-xml-reference.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/rcd-configuration-xml-reference.md)
* Service: **microsoft-identity-manager**
* Product: **identity-manager-2016**
* GitHub Login: @fimguy
* Microsoft Alias: **fimguy**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
