### ISSUE TITLE
Add On-Prem groups to B2B accouts

### ISSUE THREAD

**Issue by mrmueller** [MicrosoftDocs/MIMDocs#112]
Hi,

This is great. Very powerful.

We provide a self service portal to our users, which allows them to order applications and other stuff. After approval, ServiceNow adds the user to a group in AD (On-Prem), which grants the user access to the application. We would like to be able to do the same for our B2B users. The Problem is that we dont seem to be able to sync on-prem groups to azure B2B accounts. I guess a join in AAD Connect would be needed? Can someone offer some help? Thanks a lot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08269662-0165-5225-6da2-33bbf9989f12
* Version Independent ID: d32b3f0b-2590-a119-0ee0-bbda1652904a
* Content: [The Microsoft Identity Manager management agent for Microsoft Graph](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-graph-b2b-scenario)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-graph-b2b-scenario.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-graph-b2b-scenario.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @fimguy
* Microsoft Alias: **davidste**

**Comment by mrmueller** [comment]
To clarify:

We would like to do this because it would allow us to use myapps.microsoft.com as a central entry point for cloud apps and on-prem apps as well.

**Comment by billmath** [comment]
#please-close
