### ISSUE TITLE
Avoid Authorization_RequestDenied errors by clicking on Grant Permissions button

### ISSUE THREAD

**Issue by sheyitx** [MicrosoftDocs/MIMDocs#114]
In the section, "Authorizing the MA to manage your Azure AD directory" above, if the user does not specifically click the "Grant Permissions" button, the MIM Graph connector will throw Authorization_RequestDenied exceptions. It is a step that is very easy to miss. The documentation should explicitly call this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa92c4b-1c4e-227b-4cbb-aafc579a0c71
* Version Independent ID: 8742167d-df6b-4424-0001-9c0fa1bd569c
* Content: [The Microsoft Identity Manager management agent for Microsoft Graph](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-connector-graph#next-steps)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-connector-graph.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-connector-graph.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @fimguy
* Microsoft Alias: **davidste**

**Comment by ross-currie** [comment]
+1 to this

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
