### ISSUE TITLE
Regarding attribute precedence and reference attributes

### ISSUE THREAD

**Issue by berntjoh** [MicrosoftDocs/MIMDocs#117]
As manual precedence involves advanced flow rules and reference attributes are not allowed in advanced flow rules, will non standard precedence to supported for reference attributes? Today reference attributes work with equal precedence  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9cc9aa-1004-48e6-e4c3-2c330959cd84
* Version Independent ID: 86558ce1-cf90-e3f7-b86e-05a30efa725e
* Content: [MIM Deprecated Features And Planning For The Future](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-deprecated-features)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-deprecated-features.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-deprecated-features.md)
* Service: **microsoft-identity-manager**
* Product: **identity-manager-2016**
* GitHub Login: @barclayn
* Microsoft Alias: **davidste**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
