### ISSUE TITLE
Where to use these functions?

### ISSUE THREAD

**Issue by alfgil** [MicrosoftDocs/MIMDocs#120]
Tons of useful functions here, but I can not figure out where and how to use them? The reason the'r mentioned is probably so I would not have to write my own rule-extensions with exactly this code, but I may be wrong...??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ffb09f-fb6a-7cd5-0ad4-3ee74e2b8065
* Version Independent ID: 93b25d6d-fee4-98f4-83e6-a08b47932c85
* Content: [Functions reference for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/mim2016-functions-reference)
* Content Source: [MIMDocs/reference/mim2016-functions-reference.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/mim2016-functions-reference.md)
* Service: **microsoft-identity-manager**
* Product: **identity-manager-2016**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by barclayn** [comment]
@alfgil in the portal. Here is an example https://blogs.technet.microsoft.com/doittoit/2008/08/06/custom-expressions-in-advanced-attribute-flows/

**Comment by alfgil** [comment]
Thank you! I'm not using the portal, only the sync-engine, and I was afraid I had missed out of something I have long hoped to find in the attribute-mapping sections for "basic" FIM/MIM.
