### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by marshaljs99** [MicrosoftDocs/MIMDocs#121]
Hi, The links are broken can you please fix the hyperlinks?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45385357-e3b9-46ad-1230-98cf8ea2db35
* Version Independent ID: 85fbe629-595d-1e1c-e112-0eb59c3bc59c
* Content: [Working with Self-Service Password Reset](https://docs.microsoft.com/en-us/microsoft-identity-manager/working-with-self-service-password-reset)
* Content Source: [MIMDocs/working-with-self-service-password-reset.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/working-with-self-service-password-reset.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by markwahl-msft** [comment]
Updated.
