### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SHRPNT247** [MicrosoftDocs/MIMDocs#123]
"download" is misspelled in the line and the ``` at the end of the line is odd in the following line :
SSMS is no longer included in SQL 2016 downlaod details can be found here ```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35c89d56-ac27-c024-d0d4-1d9c3608bf33
* Version Independent ID: ab422d09-d7c1-e068-dfce-d4cdcfbcb3b9
* Content: [Configure SQL Server for Microsoft Identity Manager 2016 SP1](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-sql2016)
* Content Source: [MIMDocs/prepare-server-sql2016.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-sql2016.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **barclayn**

**Comment by markwahl-msft** [comment]
Updated.
