### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by OpaqueBlack** [MicrosoftDocs/MIMDocs#124]
There is a typo in the last sentence -- "Priviledged" should be "Privileged".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e62c6c4-7db7-d238-8283-2ffb8cb103b1
* Version Independent ID: 7038931b-2916-773c-0661-44148fd2fdd8
* Content: [PAM environment tier model](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/tier-model-for-partitioning-administrative-privileges)
* Content Source: [MIMDocs/pam/tier-model-for-partitioning-administrative-privileges.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/tier-model-for-partitioning-administrative-privileges.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by markwahl-msft** [comment]
Updated.
