### ISSUE TITLE
Error in user creation script

### ISSUE THREAD

**Issue by ddegroot0512** [MicrosoftDocs/MIMDocs#125]
I'm assuming this line
New-ADUser –SamAccountName MIMpool –name BackupAdmin
should be
New-ADUser –SamAccountName MIMpool –name MIMpool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [Set up a domain for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **barclayn**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
