### ISSUE TITLE
SQL 2017 support

### ISSUE THREAD

**Issue by pirminf** [MicrosoftDocs/MIMDocs#128]
Is SQL Server 2017 supported for MIM Sync?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3fbb109-0afc-6a7b-2486-0d6412501d10
* Version Independent ID: 54e31b36-d865-79e6-0949-3fd9a2ce6978
* Content: [Supported software platforms](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-supported-platforms)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-supported-platforms.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-supported-platforms.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by mrmueller** [comment]
Would like to know this too. Also, will it be possible to use SQL Server 2019 once it is available?

**Comment by pirminf** [comment]
Hi Martin, MIM Sync *works* very well with SQL 2017 - but still no statement if SQL 2017 and above is *supported*...

**Comment by leoerlandsson** [comment]
We'd also like to know if SQL 2017 (and Server 2019) is supported?

**Comment by markwahl-msft** [comment]
SQL Server 2017 is supported in MIM 2016 service pack 2 or a later hotfix.

**Comment by markwahl-msft** [comment]
#please-close
