### ISSUE TITLE
Picture in list "Access from the self-service portal" broken on docs.microsoft.com

### ISSUE THREAD

**Issue by bb-froggy** [MicrosoftDocs/MIMDocs#129]
The very last list contains six items. Item 5 is only a screenshot linking to media/MIM-SSPR-account-unlock.JPG. This shows fine when viewed directly on GitHub. However, when [viewed on MS Docs](https://docs.microsoft.com/en-us/microsoft-identity-manager/working-with-self-service-password-reset), Item 5 is broken into two separate items in the middle of the link. Thus, the picture is not shown.

Maybe it's because Item 5 contains only the picture but nothing else? Or is the template used to generate MS Docs broken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45385357-e3b9-46ad-1230-98cf8ea2db35
* Version Independent ID: 85fbe629-595d-1e1c-e112-0eb59c3bc59c
* Content: [Working with Self-Service Password Reset](https://docs.microsoft.com/en-us/microsoft-identity-manager/working-with-self-service-password-reset)
* Content Source: [MIMDocs/working-with-self-service-password-reset.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/working-with-self-service-password-reset.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
