### ISSUE TITLE
Feature deprecated in Windows Server 2016

### ISSUE THREAD

**Issue by hocaferr** [MicrosoftDocs/MIMDocs#130]
at the powershell command step 7, the parameter Application-Server will not work at Windows Server 2016. Reference : Additional section of MSFT documentation "Features Removed or Deprecated in Windows Server 2016" does not add any clarifications on Application Server role, referring back to the list of what has been deprecated in 2012 R2 & 2012. See also: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn303411(v=ws.11). The Application Server role is deprecated and will eventually no longer be available as an installable server role. Instead, install individual features and roles separately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9d25f8-acca-35b0-202b-f83a0a8c1e45
* Version Independent ID: bc769b6d-0c19-2590-a834-743620172fe9
* Content: [Configure Windows Server 2016 for MIM 2016 SP1](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-ws2016)
* Content Source: [MIMDocs/prepare-server-ws2016.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-ws2016.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by hocaferr** [comment]
The following features are available as part of Application Server.

.NET Framework 4.5
COM+ Network Access
Distributed Transactions
WS-Atomic Transactions
Incoming Network Transactions
Outgoing Network Transactions
TCP Port Sharing
Web Server (IIS) Support
Windows Process Activation Services
HTTP Activation
Message Queuing Activation
Named Pipes Activation
TCP Activation.
Reference: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc754024(v=ws.10)

New command line, including Sharepoint prereqs needed for MIM instalations:
Install-WindowsFeature 
NET-WCF-HTTP-Activation45,NET-WCF-TCP-Activation45,NET-WCF-Pipe-Activation45,
Web-Server, Web-WebServer, Web-Common-Http,Web-Static-Content,Web-Default-Doc, Web-Dir-Browsing,Web-Http-Errors,Web-App-Dev,
Web-Asp-Net,Web-Net-Ext,Web-ISAPI-Ext,Web-ISAPI-Filter,Web-Health,Web-Http-Logging,Web-Log-Libraries,Web-Request-Monitor,Web-Http-Tracing,Web-Security,Web-Basic-Auth,
Web-Windows-Auth,Web-Filtering,Web-Digest-Auth,Web-Performance,Web-Stat-Compression,Web-Dyn-Compression,Web-Mgmt-Tools,Web-Mgmt-Console,Web-Mgmt-Compat,Web-Metabase,
AS-Web-Support,AS-TCP-Port-Sharing,AS-WAS-Support, AS-HTTP-Activation,AS-TCP-Activation,AS-Named-Pipes,AS-Net-Framework, AS-Ent-Services, AS-Dist-Transaction, AS-WS-Atomic, AS-Incoming-Trans, AS-Outgoing-Trans, AS-TCP-Port-Sharing, AS-MSMQ-Activation
WAS,WAS-Process-Model,WAS-NET-Environment,WAS-Config-APIs, Web-Lgcy-Scripting,
Net-Framework-Features,rsat-ad-powershell,Web-Mgmt-Tools,Windows-Identity-Foundation,Server-Media-Foundation,Xps-Viewer –includeallsubfeature -restart -source d:\sources\SxS

**Comment by hocaferr** [comment]
for Windows Server 2016 the best powershell line is:
import-module ServerManager
Install-WindowsFeature `
Web-Server,`
Web-WebServer,`
Web-Common-Http,` 
Web-Static-Content,`
Web-Default-Doc,`
Web-Dir-Browsing,`
Web-Http-Errors,`
Web-App-Dev,`
Web-Asp-Net,`
Web-Net-Ext,`
Web-ISAPI-Ext,`
Web-ISAPI-Filter,`
Web-Health,`
Web-Http-Logging,`
Web-Log-Libraries,`
Web-Request-Monitor,`
Web-Http-Tracing,`
Web-Security,`
Web-Basic-Auth,`
Web-Windows-Auth,`
Web-Filtering,`
Web-Digest-Auth,`
Web-Performance,`
Web-Stat-Compression,`
Web-Dyn-Compression,`
Web-Mgmt-Tools,`
Web-Mgmt-Console,`
Web-Mgmt-Compat,`
Web-Metabase,`
Web-Lgcy-Scripting,`
NET-WCF-HTTP-Activation45,`
NET-WCF-TCP-Activation45,`
NET-WCF-Pipe-Activation45,`
NET-Framework-Features,`
NET-HTTP-Activation,`
NET-Non-HTTP-Activ,`
NET-WCF-MSMQ-Activation45,`
NET-Framework-45-ASPNET,`
NET-WCF-TCP-PortSharing45,`
NET-WCF-Services45,`
NET-Framework-45-Core,`
NET-Framework-45-Features,`
NET-Framework-Core,`
WAS,`
WAS-Process-Model,`
WAS-NET-Environment,`
WAS-Config-APIs,`
RSAT-AD-PowerShell,`
Windows-Identity-Foundation,`
Server-Media-Foundation,`
Xps-Viewer `
–includeallsubfeature -restart

**Comment by Hercules187** [comment]
As mentioned script is no longer valid follow the script at:
http://www.mim.ninja/2018/11/06/mim-2016-deployment-on-windows-2016-application-server-deprecated/

**Comment by hocaferr** [comment]
it's time to review the page and correct it.
