### ISSUE TITLE
One-Time Password SMS Gate not working

### ISSUE THREAD

**Issue by gibazza** [MicrosoftDocs/MIMDocs#131]
Using Azure Multi-Factor Authentication Server to provide MFA for the MIM SSPR reset only works with the Phone Gate workflow activity and not the One-Time Password SMS Gate. I cannot find any reference to this only working with the Phone Gate. The MIM service generates these errors under Forefront Identity Manager in the Applications and Services logs.

Error 1:
Local MFA server is supported only for STANDART mode

Error 2:
Exception: Value does not fall within the expected range.; StackTrace: at Microsoft.IdentityManagement.AzureMfaServiceProvider.PhoneAzureMfaProvider.AuthenticateLocal(PfAuthParams pfAuthParams, Int32& callStatus, Int32& errorId)
at Microsoft.IdentityManagement.AzureMfaServiceProvider.PhoneAzureMfaProvider.AzureMfaAuthenticate(PfAuthParams pfAuthParams, Int32& callStatus, Int32& errorId); InnerException null; callStatus=0, errorId=0, Certificate File Path:

Error 3:
Azure MFA: Authentication Failed. Call Status='', ErrorID='0'
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de6da5e0-b92d-fe6f-6052-294b6b9b6254
* Version Independent ID: 237cd9aa-1ea8-3f2c-9b06-c071adc519de
* Content: [Use Azure Multi-Factor Authentication Server SDK to activate PAM or SSPR Scenarios](https://docs.microsoft.com/en-gb/microsoft-identity-manager/working-with-mfaserver-for-mim)
* Content Source: [MIMDocs/working-with-mfaserver-for-mim.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/working-with-mfaserver-for-mim.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Manjunath-hk1** [comment]
@gibazza did you manage to find the workaround for these errors.

**Comment by gibazza** [comment]
@Manjunath-hk1 These errors are fixed in the latest MIM hotfixes.

**Comment by markwahl-msft** [comment]
#please-close
