### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by ReQ6W7rFnaBxyfb** [MicrosoftDocs/MIMDocs#132]
https://docs.microsoft.com/azure/active-directory/authentication/concept-sspr-howitworks.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45385357-e3b9-46ad-1230-98cf8ea2db35
* Version Independent ID: 85fbe629-595d-1e1c-e112-0eb59c3bc59c
* Content: [Working with Self-Service Password Reset](https://docs.microsoft.com/en-us/microsoft-identity-manager/working-with-self-service-password-reset)
* Content Source: [MIMDocs/working-with-self-service-password-reset.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/working-with-self-service-password-reset.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by janusmico** [comment]
Thirded.

**Comment by jordanmills** [comment]
Fourthded.

**Comment by markwahl-msft** [comment]
fixed.
