### ISSUE TITLE
SSL?

### ISSUE THREAD

**Issue by KRyan318** [MicrosoftDocs/MIMDocs#133]
This documentation states, "Be sure to configure SSL or equivalent before enabling access to this portal.." However, the script provisions the portal on port 80 without SSL. Please clarify when SSL is used. Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bb5efc7-7c39-cf26-70ef-a324d215af76
* Version Independent ID: add2ba42-a910-ce5f-3767-35834085c2fa
* Content: [Configure SharePoint for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-sharepoint)
* Content Source: [MIMDocs/prepare-server-sharepoint.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-sharepoint.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by jordanmills** [comment]
When you manually configure it without any supporting documentation.  Lol.

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
