### ISSUE TITLE
Dowload link seems broken?

### ISSUE THREAD

**Issue by Headburgh** [MicrosoftDocs/MIMDocs#136]
Download link for kb4346632 seems broken. Getting 404 error. Got any alternative links?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d8b69a-c572-fff1-6559-632ded8f9060
* Version Independent ID: 0cbcbb62-a0ee-de8f-8d1f-497a919d30ea
* Content: [Identity Manager version history](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/version-history)
* Content Source: [MIMDocs/reference/version-history.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/version-history.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by makauf** [comment]
Same on this one KB4073679

Latest Working Link is for KB4050936

**Comment by maxgaulhofer** [comment]
+1

**Comment by chadc** [comment]
Try https://support.microsoft.com/en-us/help/4469694/hotfixrolluppackagebuild452860isavailableformicrosoftidentitymanager20

**Comment by kenilelk** [comment]
Here
https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/version-history
And here
https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/version-history#version-452020
It still not fixed, not listed and had broken links to revoked 2018 year
hotfixes

**Comment by markwahl-msft** [comment]
Updated with newer hotfixes
