### ISSUE TITLE
Suggestion on account naming - get them all to use MIM*

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/MIMDocs#137]
Would be best from a sanity perspective to have SQLServer, SharePoint, BackupAdmin become MIMSQLServer, MIMSharePoint, MIMBackupAdmin.  Since we're building them for those specific functions and limiting their rights accordingly, would make sense that they are all in the same section and easy to find in AD and not scattered about alphabetically.  Plus, should help reduce risk for environments where they may have accounts of that sort of name already since adding the MIM prefix should help make it unique beyond identifying the purpose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [Set up a domain for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
