### ISSUE TITLE
Second diagram - questioning an arrow

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/MIMDocs#139]
Wouldn't the "MIM service (admin)" still point to the MIM Service database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2625af9-8587-9e56-c965-f823e6d3f3e9
* Version Independent ID: 3479cc4e-90d1-65a9-e44a-de4e46f675f7
* Content: [Topology guide for deployment](https://docs.microsoft.com/en-us/microsoft-identity-manager/topology-considerations)
* Content Source: [MIMDocs/topology-considerations.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/topology-considerations.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by bdesmond** [comment]
It should point to both the "MIM Service Database" and to the "MIM Sync Service and database"

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
