### ISSUE TITLE
Import stops at 5000 records

### ISSUE THREAD

**Issue by SimonVeale** [MicrosoftDocs/MIMDocs#140]
We’ve come across what looks like a paging bug in the Generic SQL MA which is stopping more than 5000 records importing. We’ve asked on the MIM TechNet forum and it doesn’t appear we’re doing anything wrong. 

Is there a known bug? Is there a workaround? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4776f8d9-753c-c768-c150-1ff346dee802
* Version Independent ID: 5ad3e617-31db-4fea-8435-419f09f94c50
* Content: [Generic SQL Connector step-by step](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/microsoft-identity-manager-2016-connector-genericsql-step-by-step)
* Content Source: [MIMDocs/reference/microsoft-identity-manager-2016-connector-genericsql-step-by-step.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/microsoft-identity-manager-2016-connector-genericsql-step-by-step.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by aneeshinfosec** [comment]
Download the latest version of the Generic SQL Connector, and the issue will go away :-)
https://www.microsoft.com/en-us/download/details.aspx?id=51495

**Comment by Arzamazz** [comment]
@AneeshInfoSec it is not help, MA stopping with PageSize value objects.

**Comment by Arzamazz** [comment]
I work with MySQL DB and last 1.1.913.0 SQL Generic connector

**Comment by AneeshInfoSec** [comment]
@Arzamazz it worked fine for me but I was importing from a MS SQL Server Database. I guess you raise a ticket with the MS team then. Cheers

**Comment by Arzamazz** [comment]
I solved problem with using SQL Connector verions 1.1.830, problem not appear

**Comment by markwahl-msft** [comment]
#please-close
