### ISSUE TITLE
Import stops at 5000 records

### ISSUE THREAD

**Issue by SimonVeale** [MicrosoftDocs/MIMDocs#141]
We’ve come across what looks like a paging bug in the Generic SQL MA which is stopping more than 5000 records importing. We’ve asked on the MIM TechNet forum and it doesn’t appear we’re doing anything wrong. 

Is there a known bug? Is there a workaround? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e6a7b9d-cdd0-cafd-90f5-2448c1d53cc3
* Version Independent ID: c0662eed-d361-b60d-1058-75293ddb944c
* Content: [Generic SQL Connector](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/microsoft-identity-manager-2016-connector-genericsql)
* Content Source: [MIMDocs/reference/microsoft-identity-manager-2016-connector-genericsql.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/microsoft-identity-manager-2016-connector-genericsql.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lasoke** [comment]
The  @StartIndex doesn't start at 1 as it is written in the documentation. It is start at 0.
So, the following will happen:
first page: 0 to 5000 -> For instance, in Oracle 0 is modified to 1 automatically, so you will have 5000 users
second page: 5000 to 10 000 -> you will have 5001 users, the MA will stop.
The workaround is to add 1 to the start index, so you will have:
1 to 5000 -> 5000 users
5001 to 10 000 -> 5000 users.
