### ISSUE TITLE
Missing hot fix for 4.5.286.0

### ISSUE THREAD

**Issue by iam-mike** [MicrosoftDocs/MIMDocs#142]
Download links to old hot fixes seem to have been pulled - however v 4.5.286.0 is missing entirely.

Link as of December 17, 2018: https://support.microsoft.com/en-gb/help/4469694 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d8b69a-c572-fff1-6559-632ded8f9060
* Version Independent ID: 0cbcbb62-a0ee-de8f-8d1f-497a919d30ea
* Content: [Identity Manager version history](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/version-history)
* Content Source: [MIMDocs/reference/version-history.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/version-history.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by kenilelk** [comment]
I support the claim. It is seriously mislead, and it should be fixed ASAP.

**Comment by chadc** [comment]
Try https://support.microsoft.com/en-us/help/4469694/hotfixrolluppackagebuild452860isavailableformicrosoftidentitymanager20

**Comment by IAmSuperMike** [comment]
Thanks @chadc, you’ve  linked to the same page as I. Glad it’s not just me!

**Comment by markwahl-msft** [comment]
Checked the hotfix link still working.
#please-close
