### ISSUE TITLE
Download Links broken

### ISSUE THREAD

**Issue by chadc** [MicrosoftDocs/MIMDocs#143]
After trying to figure out why the links are broken, I stumbled upon a newer version than what is listed in this doc: https://support.microsoft.com/en-us/help/4469694/hotfixrolluppackagebuild452860isavailableformicrosoftidentitymanager20.  Hope this helps someone trying to get an actual hotfix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d8b69a-c572-fff1-6559-632ded8f9060
* Version Independent ID: 0cbcbb62-a0ee-de8f-8d1f-497a919d30ea
* Content: [Identity Manager version history](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/version-history)
* Content Source: [MIMDocs/reference/version-history.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/version-history.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by reidardh** [comment]
And why MS dosn't inlude the latest version in the version document is a mystery !

**Comment by makauf** [comment]
download link/s are still broken 👎

**Comment by markwahl-msft** [comment]
Updated.
