### ISSUE TITLE
Does MIM 2016 SP1 work with SharePoint 2019

### ISSUE THREAD

**Issue by thockmanCrash** [MicrosoftDocs/MIMDocs#144]
I have downloaded PowerShell scripts to enable a SharePoint farm to integrate with MIM 2016 SP1 as the user identity provider for SharePoint (not the portal host machine, a production farm). The scripts blow up with PowerShell errors about invalid directories other invalid commands. Does anyone know if SP2019 RTM is supported with MIM 2016 SP1? If not yet, any target date?

**Comment by markwahl-msft** [comment]
SharePoint 2019 requires MIM 2016 Service Pack 2 or a later hotfix.

**Comment by markwahl-msft** [comment]
#please-close
