### ISSUE TITLE
CORP Forest Domain Requirements

### ISSUE THREAD

**Issue by mcurole** [MicrosoftDocs/MIMDocs#147]
In reading the documents, it seems an existing environment requires DC of Windows 2012 R2 or greater. Is there a specific Forest/Domain Functional level requirement to implement PAM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00ca8748-bdef-ec02-74af-6244f9bd8297
* Version Independent ID: 74f4d8bb-6a55-1e71-8b9f-03b0e47d847f
* Content: [Deploy PAM Step 1 - CORP domain](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/step-1-prepare-corp-domain)
* Content Source: [MIMDocs/pam/step-1-prepare-corp-domain.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/step-1-prepare-corp-domain.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by amasse3** [comment]
@mcurole 
In my testing, PAM will work with Corp forest at FFL 2003 or greater.  Priv forest should be FFL 2016 to take advantage of the time-bound group membership features.

**Comment by markwahl-msft** [comment]
The only requirement is on the CORP DC version of Windows Server, if you wish to use a low-RID group such as Domain Admins across forests, these should be WS 2016 or later.  We recommend a recent functional level but PAM scenario does not require it in the existing forest.

**Comment by markwahl-msft** [comment]
#please-close
