### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by mcurole** [MicrosoftDocs/MIMDocs#148]
In the note at the top on Azure MFA SDA, there is a link to the version history that is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e8079a8-0a92-e89e-b7f2-b57bd2629791
* Version Independent ID: 8848d98b-9d67-d525-ce77-a7e31d41f487
* Content: [Use Azure MFA to activate PAM](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/use-azure-mfa-for-activation)
* Content Source: [MIMDocs/pam/use-azure-mfa-for-activation.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/use-azure-mfa-for-activation.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by markwahl-msft** [comment]
Updated.
#please-close
