### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by Oricul** [MicrosoftDocs/MIMDocs#150]
This document needs to be updated with the Native client prerequisites. Refer: https://social.technet.microsoft.com/wiki/contents/articles/16682.fim-troubleshooting-synchronization-service-setup-is-having-trouble-contacting-sql-server.aspx

"SQL Client

Verify the SQL Native Client is installed on FIM."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ab9211-b85c-9668-abcb-e5195a83ac43
* Version Independent ID: 649e1fd0-fc2c-4544-ee6b-45b2e67c26e5
* Content: [Install the Microsoft Identity Manager Sync Service](https://docs.microsoft.com/en-us/microsoft-identity-manager/install-mim-sync)
* Content Source: [MIMDocs/install-mim-sync.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/install-mim-sync.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
