### ISSUE TITLE
Dead link at MinRole

### ISSUE THREAD

**Issue by craig-martin** [MicrosoftDocs/MIMDocs#152]
The URL behind MinRole (https://docs.microsoft.com/en-us/sharepoint/install/overview-of-minrole-server-roles-in-sharepoint-server-2016) no longer works

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bb5efc7-7c39-cf26-70ef-a324d215af76
* Version Independent ID: add2ba42-a910-ce5f-3767-35834085c2fa
* Content: [Configure SharePoint for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-sharepoint)
* Content Source: [MIMDocs/prepare-server-sharepoint.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-sharepoint.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by markwahl-msft** [comment]
Updated
