### ISSUE TITLE
Maybe a bit more parameters. And there are 2 mistakes in the user creation section.

### ISSUE THREAD

**Issue by guyhorn1964** [MicrosoftDocs/MIMDocs#153]
# installing MIM on 1 server. 

# reading https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain

#Param:
$DomainRoot = 'DC=test,DC=one'
$DC = 'DC1'
$DomainNetBios='test'
$MIMServiceServer = $env:COMPUTERNAME
$MIMSyncServer=$env:COMPUTERNAME
$SQLServer = $env:COMPUTERNAME
$Password = Read-Host -Prompt 'Enter password here'
$MIMAdministrationOU = 'MIMAdministration'

# construct extra params:
$path = 'OU='+ $MIMAdministrationOU + ',' + $DomainRoot 

# $ADMINcred = Get-Credential -UserName 'TEST\SGADMIN' -Message 'DAAHHH'

New-ADOrganizationalUnit -Name MIMAdministration -Path $DomainRoot

import-module activedirectory
$sp = ConvertTo-SecureString $password –asplaintext –force

New-ADUser –SamAccountName MIMINSTALL –name MIMINSTALL -Path $path
Set-ADAccountPassword –identity MIMINSTALL –NewPassword $sp
Set-ADUser –identity MIMINSTALL –Enabled 1 –PasswordNeverExpires 1

New-ADUser –SamAccountName MIMMA –name MIMMA -Path $path
Set-ADAccountPassword –identity MIMMA –NewPassword $sp
Set-ADUser –identity MIMMA –Enabled 1 –PasswordNeverExpires 1

New-ADUser –SamAccountName MIMSync –name MIMSync -Path $path
Set-ADAccountPassword –identity MIMSync –NewPassword $sp
Set-ADUser –identity MIMSync –Enabled 1 –PasswordNeverExpires 1

New-ADUser –SamAccountName MIMService –name MIMService -Path $path
Set-ADAccountPassword –identity MIMService –NewPassword $sp
Set-ADUser –identity MIMService –Enabled 1 –PasswordNeverExpires 1

New-ADUser –SamAccountName MIMSSPR –name MIMSSPR -Path $path
Set-ADAccountPassword –identity MIMSSPR –NewPassword $sp
Set-ADUser –identity MIMSSPR –Enabled 1 –PasswordNeverExpires 1

New-ADUser –SamAccountName SharePoint –name SharePoint -Path $path
Set-ADAccountPassword –identity SharePoint –NewPassword $sp
Set-ADUser –identity SharePoint –Enabled 1 –PasswordNeverExpires 1

New-ADUser –SamAccountName SqlServer –name SqlServer -Path $path
Set-ADAccountPassword –identity SqlServer –NewPassword $sp
Set-ADUser –identity SqlServer –Enabled 1 –PasswordNeverExpires 1

New-ADUser –SamAccountName BackupAdmin –name BackupAdmin -Path $path
Set-ADAccountPassword –identity BackupAdmin –NewPassword $sp
Set-ADUser –identity BackupAdmin –Enabled 1 -PasswordNeverExpires 1

New-ADUser –SamAccountName MIMpool –name MIMpool -Path $path
Set-ADAccountPassword –identity MIMPool –NewPassword $sp
Set-ADUser –identity MIMPool –Enabled 1 -PasswordNeverExpires 1

##################

New-ADGroup –name MIMSyncAdmins –GroupCategory Security –GroupScope Global –SamAccountName MIMSyncAdmins -Path $path
New-ADGroup –name MIMSyncOperators –GroupCategory Security –GroupScope Global –SamAccountName MIMSyncOperators -Path $path
New-ADGroup –name MIMSyncJoiners –GroupCategory Security –GroupScope Global –SamAccountName MIMSyncJoiners -Path $path
New-ADGroup –name MIMSyncBrowse –GroupCategory Security –GroupScope Global –SamAccountName MIMSyncBrowse -Path $path
New-ADGroup –name MIMSyncPasswordReset –GroupCategory Security –GroupScope Global –SamAccountName MIMSyncPasswordSet -Path $path
Add-ADGroupMember -identity MIMSyncAdmins -Members sgadmin
Add-ADGroupmember -identity MIMSyncAdmins -Members MIMService
Add-ADGroupmember -identity MIMSyncAdmins -Members MIMInstall

##################

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [Set up a domain for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by guyhorn1964** [comment]
Cant edit it :-(

**Comment by kong-zz** [comment]
My simple version. Basically, we need to add A records in DNS server first before adding SPNs to enable Kerberos authentication for service accounts.

Import-Module ActiveDirectory

#1. Create the following user accounts for MIM services
$sp = ConvertTo-SecureString "Pass@word1" -AsPlainText -Force
$mimAccs = "mimInstall","mimMA","mimSync","mimSvc","mimSSPR","mimSP","mimSQL","mimBackupAdmin", "mimPool"
foreach ($mimAcc in $mimAccs)
{
    New-ADUser –SamAccountName $mimAcc –name $mimAcc
    Set-ADAccountPassword –identity $mimAcc –NewPassword $sp
    Set-ADUser –identity $mimAcc –Enabled 1 –PasswordNeverExpires 1
}

#2. Create security groups to all the groups.
$ouPath = "ou=SharePoint2016,ou=ManagedServiceAccounts,DC=Klmonkey,DC=com"
$secGroupNames = "MIMSyncAdmins","MIMSyncOperators","MIMSyncJoiners","MIMSyncBrowse","MIMSyncPasswordReset"
foreach ($secGroupName in $secGroupNames)
{
    New-ADGroup -Name secGroupName –GroupCategory Security –GroupScope Global –SamAccountName secGroupName -Path $ouPath
}
Add-ADGroupMember -identity MIMSyncAdmins -Members Administrator
Add-ADGroupmember -identity MIMSyncAdmins -Members mimSvc
Add-ADGroupmember -identity MIMSyncAdmins -Members mimInstall

#3. Add the following DNS 'A' records in the DNS server for proper name resolution
#   mim.contoso.com Point to intranet physical ip address
#   passwordreset.contoso.com Point to intranet physical ip address
#   passwordregistration.contoso.com Point to intranet physical ip address

#4. Add SPNs to enable Kerberos authentication for service accounts
setspn -S http/mim.klmonkey.com klmonkey\mimPool
setspn -S http/mim klmonkey\mimPool
setspn -S http/passwordreset.klmonkey.com klmonkey\mimSSPR
setspn -S http/passwordregistration.klmonkey.com klmonkey\mimSSPR
setspn -S FIMService/mim.klmonkey.com klmonkey\mimSvc
setspn -S FIMService/intranet.klmonkey.com klmonkey\mimSvc

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
