### ISSUE TITLE
When will the master be released?

### ISSUE THREAD

**Issue by paule96** [MicrosoftDocs/MIMDocs#154]
Hi guys,

This documentation have some wired bugs on the docs.com site. (live)

When the master goes live so we all can use the docs.com site again instead of this github repository? 

I'm mean the quickstart is completly broken and have wrong sampels. Like it is describte in issue #102 or the fix of the typos that are mentioned [here](https://github.com/MicrosoftDocs/MIMDocs/issues/103). They are all fixed in master branch. And some of the bugs are also fixed in the live branch. But there a not live at docs.com? where is the issue?

**Comment by paule96** [comment]
ping @kgremban

**Comment by kgremban** [comment]
@billmath can you take a look at this?

**Comment by paule96** [comment]
@kgremban & @billmath any body here 📣

**Comment by billmath** [comment]
@paule96 Sorry for the delay and thanks for bringing this to our attention.  I am going to open a ticket with our publishing folks and have them look into this.   I will follow-up once I know more.

**Comment by paule96** [comment]
@billmath thanks :) Hope we can fix this. MIM is a cool tool, so make the docs great again 👍

**Comment by paule96** [comment]
@billmath are there any updates?

**Comment by paule96** [comment]
@kgremban and @billmath hello guys,

have we any progress here?

**Comment by paule96** [comment]
Hi @rjagiewich,

you commited in last time to master. Can you get me any response to my issue here? The other two people don't respond here… :(

**Comment by paule96** [comment]
after a half year I ask again, are there any updates to this? @billmath , @kgremban , @rjagiewich

**Comment by rjagiewich** [comment]
Hi @paul96, I'm not the person to ask about this, sorry. I just review PRs that come into the PR queue. Thanks! -Rebecca

**Comment by paule96** [comment]
Sad to hear that... Maybe you know someone that can help here...

**Comment by paule96** [comment]
@billmath can you tell us the status of the ticket?

**Comment by paule96** [comment]
@billmath & @kgremban are there any updates, a half year later again?

**Comment by paule96** [comment]
I think it is only merging master to live and the release process will start. It's looking for me like just that. Because the last change on the branch live is 3 years ago. Like all the pages on docs.com. So can we just create a new PR from master to live? And then we just must press merge and the docs are up to date? 
That will add over 200 commits to the live version. So I think that will also fix most of the issues that exist in this repo.

Here are some examples:

#200
#196
#175
#174

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
