### ISSUE TITLE
Download link to Visual Studio My Benefits doesn't seem to work

### ISSUE THREAD

**Issue by MarkJaroski** [MicrosoftDocs/MIMDocs#155]
When I follow the link I get a page reading:  We didn't find results for "Microsoft Identity Manager 2016 with Service Pack 1"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab7d8f95-fc1f-174f-e7da-d83504d5829c
* Version Independent ID: c30fa3fe-1aa1-5d54-fa88-eae462a38da1
* Content: [Microsoft Identity Manager licensing and downloads](https://docs.microsoft.com/en-gb/microsoft-identity-manager/microsoft-identity-manager-licensing#feedback)
* Content Source: [MIMDocs/microsoft-identity-manager-licensing.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-licensing.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **markwahl-msft**

**Comment by markwahl-msft** [comment]
Microsoft Identity Manager downloads for dev/test from Visual Studio my benefits is currently available for Visual Studio subscription levels "Visual Studio Enterprise with MSDN / Visual Studio Enterprise - annual" and "MSDN Platforms".  To learn more, on the page https://visualstudio.microsoft.com/vs/pricing-details/ change to "standard subscriptions" and search for "Software for dev/test".  There will be a link for spreadsheet with the list of downloads included for each subscription level.

**Comment by markwahl-msft** [comment]
#please-close
