### ISSUE TITLE
Provisioning for sql database

### ISSUE THREAD

**Issue by Roopalityagi** [MicrosoftDocs/MIMDocs#156]
I want to know ho do we provision a user from sql database to active directory. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7d8ad1e-df34-629f-e05d-0a7683b2f1eb
* Version Independent ID: 3c1a9981-7c98-49d1-ba85-5292bbabd7c2
* Content: [Microsoft Identity Manager 2016 user provisioning to AD](https://docs.microsoft.com/en-us/microsoft-identity-manager/mim-how-provision-users-adds#feedback)
* Content Source: [MIMDocs/mim-how-provision-users-adds.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/mim-how-provision-users-adds.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by markwahl-msft** [comment]
Closing as a question rather than a documentation issue.
