### ISSUE TITLE
Sharepoint 2016 on server 2016 pre-reqs wont install

### ISSUE THREAD

**Issue by Hercules187** [MicrosoftDocs/MIMDocs#157]
Need to follow this solution http://www.mim.ninja/2018/11/06/mim-2016-deployment-on-windows-2016-application-server-deprecated/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bb5efc7-7c39-cf26-70ef-a324d215af76
* Version Independent ID: add2ba42-a910-ce5f-3767-35834085c2fa
* Content: [Configure SharePoint for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-sharepoint#feedback)
* Content Source: [MIMDocs/prepare-server-sharepoint.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-sharepoint.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by dieterschelkens** [comment]
If you mean by won't install that you get download errors, try disabling the IE Enhanced Security (located at Local Server properties in the Server Manager). And enable downloads in Internet Explorer security. This fixed the prerequisites installer for me.

**Comment by jordanmills** [comment]
It's a bug in the prerequisites bootstrapper on windows server 2016+.  Install .NET 3.5 through server manager (or powershell) (and specify the sxs location) manually. Then run the prerequisite bootstrapper again.  If it still doesn't work, install the remaining required server features the same way, then try again.

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
