### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vimochan** [MicrosoftDocs/MIMDocs#158]
Do I need a full blown MIM installation to implement only Password Sync between 2 AD domains? If not what do I need at a minimum?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 743703aa-1f15-472a-d5f3-972cfd19f324
* Version Independent ID: ad1e4184-0c88-f18b-1fa9-67fe3767d988
* Content: [Deploy the password change notification service](https://docs.microsoft.com/en-us/microsoft-identity-manager/deploying-mim-password-change-notification-service-on-domain-controller#feedback)
* Content Source: [MIMDocs/deploying-mim-password-change-notification-service-on-domain-controller.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/deploying-mim-password-change-notification-service-on-domain-controller.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Arzamazz** [comment]
Hi, you may install only Sync Service (without Portal)+ PCNS on DC.

**Comment by markwahl-msft** [comment]
#please-close
