### ISSUE TITLE
Insufficient documentation around web.config settings.

### ISSUE THREAD

**Issue by estenrye** [MicrosoftDocs/MIMDocs#159]
Where do I find the web config file I need to modify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72dedca1-399d-bba8-7a5a-7100d6cc0da8
* Version Independent ID: dc3c5b50-86ef-7a85-4a15-2313014d1dc5
* Content: [Certificate Management REST API service details](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/certificate-management-rest-api-service-details#feedback)
* Content Source: [MIMDocs/reference/certificate-management-rest-api-service-details.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/certificate-management-rest-api-service-details.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
