### ISSUE TITLE
CORPDC in Contoso?

### ISSUE THREAD

**Issue by MWRobertson** [MicrosoftDocs/MIMDocs#160]
It seems logical, but just to confirm - CORPDC and CORPWKSTN are joined to CONTOSO. Is that correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 984878ee-c1a7-2171-0335-4d7095cecb88
* Version Independent ID: d9acfad4-8339-1435-8a95-78b1c40bab2c
* Content: [Configure MIM 2016 for Privileged Access Management](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/configuring-mim-environment-for-pam#feedback)
* Content Source: [MIMDocs/pam/configuring-mim-environment-for-pam.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/configuring-mim-environment-for-pam.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lassaad2k** [comment]
Yes ,beause the trust between PRIV and CONTOSO forests.
 PRIVDC and CORPDC are in different Forests .

**Comment by markwahl-msft** [comment]
#please-close
