### ISSUE TITLE
Is SQL Server 2012 SP4 Supported?

### ISSUE THREAD

**Issue by alicain** [MicrosoftDocs/MIMDocs#161]
Can it please be clarified if SQL 2012 SP4 is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3fbb109-0afc-6a7b-2486-0d6412501d10
* Version Independent ID: 54e31b36-d865-79e6-0949-3fd9a2ce6978
* Content: [Supported software platforms](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-supported-platforms#feedback)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-supported-platforms.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-supported-platforms.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by markwahl-msft** [comment]
Please note that SQL Server 2012 Service Pack 4 itself is no longer in mainstream support, it is in extended support.

**Comment by markwahl-msft** [comment]
#please-close
