### ISSUE TITLE
1.Login as a domain administrator -> schema admin too.

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/MIMDocs#163]
You're going to be extending the schema. Need to log in with a user with that ability, not just domain admin rights..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 743703aa-1f15-472a-d5f3-972cfd19f324
* Version Independent ID: ad1e4184-0c88-f18b-1fa9-67fe3767d988
* Content: [Deploy the password change notification service](https://docs.microsoft.com/en-us/microsoft-identity-manager/deploying-mim-password-change-notification-service-on-domain-controller)
* Content Source: [MIMDocs/deploying-mim-password-change-notification-service-on-domain-controller.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/deploying-mim-password-change-notification-service-on-domain-controller.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
