### ISSUE TITLE
Still having access denied 

### ISSUE THREAD

**Issue by Safaelmi** [MicrosoftDocs/MIMDocs#164]
i followed all steps in https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/configuring-mim-environment-for-pam . but the dir command fails with the error message Access is denied, i re-check the trust relationship like they mention it's well configured. i still can't access to the file shared .
request status : processing 
all steps are configured plz any helps thank you in advance .

**Comment by markwahl-msft** [comment]
Closing github issue as this is a support question rather than a documentation issue.
