### ISSUE TITLE
MIM 2016 SP1 with SharePoint 2019: read-error after the PhotoStoreUpdate

### ISSUE THREAD

**Issue by RomanMazanka** [MicrosoftDocs/MIMDocs#167]
I've configured MIM 2016 and performed a full synchronization. Then I've executed Update-SPProfilePhotoStore cmdlet to have the pictures generated. After that, I run full user sync again and have "completed-discovery-errors" on SPMA-FullImport task. Discovery errors are "read-error".

After some investigation, I found out that this is because of image URLs - MIM tries to verify the images. I've turned on trace logs in IIS and noticed that there are many anonymous requests to MySite Web Application. Then I found a post where SharePoint guy advised to allow anonymous access to the Picture Library. I've done that, but the error still persists. I continue IIS log review and see a lot of 401 errors on CA Web Application on /_vti_bin/ProfileImportExportService.asmx endpoint.

Note:
SharePoint 2019 (April 2019 CU)
MIM 2016 SP1 (4.4.1642.0)
Windows Server 2016 Datacenter (Build 14393)

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
