### ISSUE TITLE
It looks harder to understand at a first glance. It requires more explanation.

### ISSUE THREAD

**Issue by akarthickarun** [MicrosoftDocs/MIMDocs#170]
Does virtual machines (VMs) with separate drives mean that each virtual machine has to be installed on separate physical hard drive?  
 
Or can all VMs be installed on a separate logical volume in a single hard drive? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f662a4c-f87f-fd2b-e89c-299c8c3bc7d6
* Version Independent ID: 0f2f22cc-c7e2-80a6-9a36-3656694b1c4b
* Content: [PAM environment overview](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/environment-overview#feedback)
* Content Source: [MIMDocs/pam/environment-overview.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/environment-overview.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by markwahl-msft** [comment]
separate logical drives.
