### ISSUE TITLE
My simple version for DEV env. 

### ISSUE THREAD

**Issue by kong-zz** [MicrosoftDocs/MIMDocs#171]
My simple version. Basically, we need to add A records in DNS server first before adding SPNs to enable Kerberos authentication for service accounts.

Import-Module ActiveDirectory

#1. Create the following user accounts for MIM services
$sp = ConvertTo-SecureString "Pass@word1" -AsPlainText -Force
$mimAccs = "mimInstall","mimMA","mimSync","mimSvc","mimSSPR","mimSP","mimSQL","mimBackupAdmin", "mimPool"
foreach ($mimAcc in $mimAccs)
{
New-ADUser –SamAccountName $mimAcc –name $mimAcc
Set-ADAccountPassword –identity $mimAcc –NewPassword $sp
Set-ADUser –identity $mimAcc –Enabled 1 –PasswordNeverExpires 1
}

#2. Create security groups to all the groups.
$ouPath = "ou=SharePoint2016,ou=ManagedServiceAccounts,DC=Klmonkey,DC=com"
$secGroupNames = "MIMSyncAdmins","MIMSyncOperators","MIMSyncJoiners","MIMSyncBrowse","MIMSyncPasswordReset"
foreach ($secGroupName in $secGroupNames)
{
New-ADGroup -Name secGroupName –GroupCategory Security –GroupScope Global –SamAccountName secGroupName -Path $ouPath
}
Add-ADGroupMember -identity MIMSyncAdmins -Members Administrator
Add-ADGroupmember -identity MIMSyncAdmins -Members mimSvc
Add-ADGroupmember -identity MIMSyncAdmins -Members mimInstall

#3. Add the following DNS 'A' records in the DNS server for proper name resolution

mim.contoso.com Point to intranet physical ip address
passwordreset.contoso.com Point to intranet physical ip address
passwordregistration.contoso.com Point to intranet physical ip address
#4. Add SPNs to enable Kerberos authentication for service accounts
setspn -S http/mim.klmonkey.com klmonkey\mimPool
setspn -S http/mim klmonkey\mimPool
setspn -S http/passwordreset.klmonkey.com klmonkey\mimSSPR
setspn -S http/passwordregistration.klmonkey.com klmonkey\mimSSPR
setspn -S FIMService/mim.klmonkey.com klmonkey\mimSvc
setspn -S FIMService/intranet.klmonkey.com klmonkey\mimSvc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [Set up a domain for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain#feedback)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
