### ISSUE TITLE
Wrong Powershell

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/MIMDocs#175]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/MIMDocs.ja-jp/issues/16
The user is suggesting a fix in the code.

@yang-jiayi commented 9 hours ago
Hey,

New-ADUser –SamAccountName MIMpool –name BackupAdmin
is wrong.

New-ADUser –SamAccountName MIMpool –name MIMpool
is right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [Set up a domain for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain#feedback)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by xardalodin** [comment]
they will never fix this

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
