### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by japerez17** [MicrosoftDocs/MIMDocs#178]
When installing the Service and Portal I get an error trying to connect to the server. I'm following the steps and the instance is working fine. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 075343f5-fb83-36e7-2b3f-667aed1bda45
* Version Independent ID: a0962eb3-fa18-f808-818d-1d76c803045a
* Content: [Install Microsoft Identity Manager Service and Portal](https://docs.microsoft.com/en-us/microsoft-identity-manager/install-mim-service-portal#feedback)
* Content Source: [MIMDocs/install-mim-service-portal.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/install-mim-service-portal.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by jontheitpro** [comment]
In our testing, this connection requires TLS 1.0 (and appears to be forced by the installation wizard)

**Comment by amasse3** [comment]
@japerez17 If you are using a named SQL instance, make sure you open the additional required ports in the firewall.  https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port?view=sql-server-ver15

**Comment by markwahl-msft** [comment]
#please-close
