### ISSUE TITLE
UoCDropDownList Default Value

### ISSUE THREAD

**Issue by IanBassi** [MicrosoftDocs/MIMDocs#181]
UoCDropDownList has not been updated with the Default Value option which was added in this hotfix.
https://support.microsoft.com/en-us/help/4012498/hotfix-rollup-package-build-4-4-1459-0-is-available-for-microsoft-iden

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1584e6a9-c3cc-d7b7-2703-53e43814b5da
* Version Independent ID: ee693503-56e7-1ce2-648e-385be0eabb4e
* Content: [Resource control display configuration XML reference](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/rcd-configuration-xml-reference#feedback)
* Content Source: [MIMDocs/reference/rcd-configuration-xml-reference.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/rcd-configuration-xml-reference.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
