### ISSUE TITLE
MIM Service and Portal installation ended prematurely 

### ISSUE THREAD

**Issue by zahrajuma** [MicrosoftDocs/MIMDocs#182]
I have an issued when installing the service and portal on the MIM server. Whenever I try to install it shows me the following error: 
"The features you have selected have the following prerequisites. Refer to the installation guide for more information. Please update your machine and retry the installation.
- Sharepoint

Even though I have SharePoint installed on the MIM server. 

I am attaching the installation log for viewing, please advise on this issue. 
[install.log](https://github.com/MicrosoftDocs/MIMDocs/files/3724635/install.log)

**Comment by markwahl-msft** [comment]
Closing as this is a support issue rather than a documentation issue.
