### ISSUE TITLE
More informations about supported browsers for portal

### ISSUE THREAD

**Issue by itch76** [MicrosoftDocs/MIMDocs#183]
Hello,
As said in this page, supported browser for MIM 2016 SP1 portal are : 
MIM Service and Portal --&gt; Browser --&gt; "All major supported browsers"
Ok, so supported browsers are ... the supported browsers... ?
Can we have a list of browsers and minimum version that has been tested and validated?
Regards,
Maxime

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3fbb109-0afc-6a7b-2486-0d6412501d10
* Version Independent ID: 54e31b36-d865-79e6-0949-3fd9a2ce6978
* Content: [Supported software platforms](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-supported-platforms#feedback)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-supported-platforms.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-supported-platforms.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
