### ISSUE TITLE
Related topic links to this same page

### ISSUE THREAD

**Issue by cabtilx** [MicrosoftDocs/MIMDocs#184]
Learn more on scenarios added in MIM 2016 and earlier at Microsoft Identity manager 2016. Just links back to this page. In many ways I guess it is a related topic in that it's identical

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea2a5249-61f8-bc0d-82bc-d2b5d1e11b79
* Version Independent ID: 79f5a969-4bcd-ceba-7770-7069f723d8bf
* Content: [Microsoft Identity Manager](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016#feedback)
* Content Source: [MIMDocs/microsoft-identity-manager-2016.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
