### ISSUE TITLE
BHOLD version 6.0.62.0 release notes

### ISSUE THREAD

**Issue by mvaneijken** [MicrosoftDocs/MIMDocs#185]
BHOLD version 6.0.62.0 is shiped with MIM 2016 SP2, but any release notes are missing. Could you please provide release information about that version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4d2885b-dae0-2418-fe17-b033c322e8b5
* Version Independent ID: 52030f0b-7d54-b69a-d03c-c52bcf2a8af1
* Content: [Identity Manager BHOLD version history](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/version-bhold-history#feedback)
* Content Source: [MIMDocs/reference/version-bhold-history.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/version-bhold-history.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
