### ISSUE TITLE
No link

### ISSUE THREAD

**Issue by mlondon215** [MicrosoftDocs/MIMDocs#186]
In the pre-req section, item 2 states: "REST data source sample service is deployed. Download and install the sample from (see here)." but "see here" is not a hyperlink.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 482c95b8-49c1-02d7-31eb-82aa326e45a6
* Version Independent ID: 46fa5700-c61e-2b57-bab1-06d7d118fb00
* Content: [Web Service Connector workflow guide for the REST API](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/microsoft-identity-manager-2016-ma-ws-restgeneric#feedback)
* Content Source: [MIMDocs/reference/microsoft-identity-manager-2016-ma-ws-restgeneric.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/microsoft-identity-manager-2016-ma-ws-restgeneric.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
