### ISSUE TITLE
BHOLD ?

### ISSUE THREAD

**Issue by TheOtherBillGates** [MicrosoftDocs/MIMDocs#188]
Can you make a slight effort, a minimum effort and maybe, just maybe explain what BHOLD acronym stands for ? We humans, cannot guess it unfortunately !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad4952bf-8907-5169-0dd2-bfd5160dcaae
* Version Independent ID: 8c296be4-efcc-ab64-2f3f-440aed8ffeca
* Content: [Microsoft BHOLD Suite Concepts Guide](https://docs.microsoft.com/en-us/microsoft-identity-manager/bhold/bhold-concepts-guide)
* Content Source: [MIMDocs/bhold/bhold-concepts-guide.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/bhold/bhold-concepts-guide.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by kenilelk** [comment]
Hi,
BHOLD case is a very typical story. Please have a look
https://www.crunchbase.com/organization/bhold-company#section-overview

**Comment by markwahl-msft** [comment]
Sorry, BHOLD is not an acronym, it is a brand name for the role management additions to FIM/MIM.

**Comment by markwahl-msft** [comment]
#please-close
