### ISSUE TITLE
Image at top is wrong

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/MIMDocs#189]
The Green should be AD DS(CORPDC) not AD DS(PRIVDC). Blue is Priv Domain

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f662a4c-f87f-fd2b-e89c-299c8c3bc7d6
* Version Independent ID: 0f2f22cc-c7e2-80a6-9a36-3656694b1c4b
* Content: [PAM environment overview](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/environment-overview#feedback)
* Content Source: [MIMDocs/pam/environment-overview.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/environment-overview.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
