### ISSUE TITLE
netdom trust command

### ISSUE THREAD

**Issue by murasamelabo** [MicrosoftDocs/MIMDocs#190]
I think **"Give forests read access to Active Directory"** step 10's second command is wrong.
domain name "contoso.local" is missing

### original
```
netdom trust contoso.local /quarantine:no /domain priv.contoso.local
netdom trust /enablesidhistory:yes /domain priv.contoso.local
```

### correct 
```
netdom trust contoso.local /quarantine:no /domain priv.contoso.local
netdom trust contoso.local /enablesidhistory:yes /domain priv.contoso.local
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67377ebe-91dc-a93f-2d22-fcc65799e598
* Version Independent ID: a294d089-fc1a-a8d9-3f45-4fa2fc48e53d
* Content: [Deploy PAM step 5 – Forest link](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/step-5-establish-trust-between-priv-corp-forests#feedback)
* Content Source: [MIMDocs/pam/step-5-establish-trust-between-priv-corp-forests.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/step-5-establish-trust-between-priv-corp-forests.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by CoadyTech** [comment]
I've just verified this now. The secondary netdom command in the article fails to run. Changes by @murasamelabo do run correctly.

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
