### ISSUE TITLE
Prepare SharePoint to host the MIM Portal Step 4 needs to be step 6

### ISSUE THREAD

**Issue by damianscoles** [MicrosoftDocs/MIMDocs#192]
In the section "Prepare SharePoint to host the MIM Portal", Step 4 needs to be moved down between Steps 6 and 7.  Otherwise, the MIM Portal page does not load properly.  If, however Steps 5 and 6 are performed, then step 4, the MIM Portal loads.  Was able to reproduce this twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bb5efc7-7c39-cf26-70ef-a324d215af76
* Version Independent ID: add2ba42-a910-ce5f-3767-35834085c2fa
* Content: [Configure SharePoint for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-sharepoint#feedback)
* Content Source: [MIMDocs/prepare-server-sharepoint.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-sharepoint.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
