### ISSUE TITLE
SQL permissions

### ISSUE THREAD

**Issue by cvostinar** [MicrosoftDocs/MIMDocs#193]
Would be great to have mentioned in this guide that the Sync service account requires SQL sysadmin role on the server hosting the DB.
Would also be helpful to mention here as well to install the SQL native client so that the installer can query the SQL DB.
The sysadmin permissions of the sync service account can be downgraded to db_owner after the install as most, if not all DBAs would be uncomfortable, for good reason, with a service account having sysadmin rights.
Also, running the installer as the service account is required and that is not mentioned anywhere here.
This could typically be a problem in most organizations whereby interactive and local logons are prohibited on service accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ab9211-b85c-9668-abcb-e5195a83ac43
* Version Independent ID: 649e1fd0-fc2c-4544-ee6b-45b2e67c26e5
* Content: [Install the Microsoft Identity Manager Sync Service](https://docs.microsoft.com/en-us/microsoft-identity-manager/install-mim-sync#feedback)
* Content Source: [MIMDocs/install-mim-sync.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/install-mim-sync.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
