### ISSUE TITLE
Install MIM 2016: MIM Service and Portal - Installation Prerequisites Not Met

### ISSUE THREAD

**Issue by DerGemeine** [MicrosoftDocs/MIMDocs#194]
Hey,
I have the following setup.

OS: Windows Server 2019
IIS: 10.0.17763.1
SP: 2016 - Compatibility Level 15
SQL: MSSQL 2016 SP2

I have one AD server and one Identity Management Server (which is standalone), on which I have installed the SQL, IIS and MIM Sync Service onto.

Now I am trying to install the Service and Portal via the setup.exe, when I click next on the page for the feature selection I get an error message, saying: 

"The features you have selected have the following prerequisites. Refer to the installation guide for more information. Please update your machine and retry the installation.

- IIS 7.0 or better.
-SharePoint."

I tried googling it, but nothing has helped so far.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab7d8f95-fc1f-174f-e7da-d83504d5829c
* Version Independent ID: c30fa3fe-1aa1-5d54-fa88-eae462a38da1
* Content: [Microsoft Identity Manager licensing and downloads](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-licensing#feedback)
* Content Source: [MIMDocs/microsoft-identity-manager-licensing.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-licensing.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **mwahl**

**Comment by gibazza** [comment]
Hi,

Do you have the MIM install media with SP1 integrated? If not that is going to be the issue as I believe SP 2016 is not supported pre SP1.

**Comment by DerGemeine** [comment]
Hey, thanks for your response. 

It seems that I do have just the standard without the SP1, but how am I able to install this at an SP1 level? I am only able to find updates to apply when the MIM is already installed. Also the installation of the Sync Service did work without any issues.

**Comment by gibazza** [comment]
If you can't download the media with SP1 integrated from https://my.visualstudio.com/Downloads with your VS subscription then you would have to install an earlier version of SP, then upgrade MIM to SP1 or later, and finally upgrade to SP 2016. Or you could try slipstream SP1 update into your pre-SP1 install media (I did try this but couldn't get it to work).

**Comment by DerGemeine** [comment]
Hello, thanks for your response.

I tried installing it now with SP Foundation 2013, throws me an "disp_e_exception" error, I will try with Windows Server 2016 now.

**Comment by DerGemeine** [comment]
Okay, so the installation itself did work without any errors, however I am not able to reach the http://mim.mydomain.mytld/identitymanagement address. Do you have any ideas? I can reach http://mim.mydomain.mytld/ just fine.

**Comment by gibazza** [comment]
Do you see any error messages when browsing to http://mim.mydomain.mytld/identitymanagement? If there are no error messages are you prompted for credentials? Do you see a blank page?

**Comment by DerGemeine** [comment]
Hey, thanks for response once again! 

It's just a blank page when I navigate to the mim.mydomain.mytld/identitymanagement, also I just checked, I don't have access to the sync service, but I can see it's up and running.

**Comment by gibazza** [comment]
No problem. Getting the MIM portal up and running can be painful.

This is an authN issue. Did you set up the SPN detailed here https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain in section 4? 
Make sure you have a DNS A record for mim.mydomain.mytld
Run the first and last commands replacing Contoso\mimpool with the service account you created Sharpoint e.g.
setspn -S http/mim.mydomain.mytld domain\[SP Service account name]
and the last 2 command  with the service account for the mim service e.g
setspn -s FIMService/mim.mydomain.mytld domain\[MIM Service account name]

Also, make sure you use IE and add mim.mydomain.mytld as a trusted or intranet site in the security settings.

**Comment by DerGemeine** [comment]
Hello, thanks.

1. Yes I created th SPNs, I'll share them here (in german tho) because I don't think they're confidential and are not reachable from outside:
![grafik](https://user-images.githubusercontent.com/23128074/73685275-27988f80-46c6-11ea-8fc7-5c2df7d9466b.png)

2. DNS Records are created:
![Screenshot_2](https://user-images.githubusercontent.com/23128074/73685369-57e02e00-46c6-11ea-8593-cad14354add8.png)

3. Site added to the intranet:
![Screenshot_3](https://user-images.githubusercontent.com/23128074/73685424-6c242b00-46c6-11ea-9074-fe2e78d05c52.png)


So now I used the standard Domain Administrator (he's in the MIMSyncAdmins group, the user I used to access it before wasn't a member of this group, lol) to login into mim.mydomain.mytld/identitymanagement. The popup for the login credentials comes up, but when I supply them theres just a 404 coming up.

Thanks

**Comment by istrouser** [comment]
> Hello, thanks.
> 
> 1. Yes I created th SPNs, I'll share them here (in german tho) because I don't think they're confidential and are not reachable from outside:
>    ![grafik](https://user-images.githubusercontent.com/23128074/73685275-27988f80-46c6-11ea-8fc7-5c2df7d9466b.png)
> 2. DNS Records are created:
>    ![Screenshot_2](https://user-images.githubusercontent.com/23128074/73685369-57e02e00-46c6-11ea-8593-cad14354add8.png)
> 3. Site added to the intranet:
>    ![Screenshot_3](https://user-images.githubusercontent.com/23128074/73685424-6c242b00-46c6-11ea-9074-fe2e78d05c52.png)
> 
> So now I used the standard Domain Administrator (he's in the MIMSyncAdmins group, the user I used to access it before wasn't a member of this group, lol) to login into mim.mydomain.mytld/identitymanagement. The popup for the login credentials comes up, but when I supply them theres just a 404 coming up.
> 
> Thanks

I think this 404 issue is caused by a different SharePoint language version. I met the same issue when I use SharePoint 2016 Chinese version. I re-installed it with English version. It was solved. For your reference.

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
