### ISSUE TITLE
schusestrongcrypto keys are also required when setting up TLS 1.2

### ISSUE THREAD

**Issue by luisfeliz79** [MicrosoftDocs/MIMDocs#195]
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#schusestrongcrypto

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb8e2cf-1d18-bdbd-7127-d138312bbdae
* Version Independent ID: 628cec97-b75f-b4eb-2c40-1bd459bca5b3
* Content: [Planning Microsoft Identity Manager 2016 in TLS 1.2 environment](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-tls)
* Content Source: [MIMDocs/preparing-tls.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-tls.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
