### ISSUE TITLE
Set SPN for svcMIMAppPool is not working ==> no gMSA

### ISSUE THREAD

**Issue by Schliefer86** [MicrosoftDocs/MIMDocs#196]
The Command for the svcMIMAppPool Account to set the SPN is not Working because the account is no Groupmanaged Service Account.
 Replace ==&gt; Set-ADServiceAccount -Identity svcMIMAppPool -ServicePrincipalNames @{Add="http/mim.contoso.com"}
 With ==&gt; setspn -S http/mim.contoso.com contoso\svcMIMAppPool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b72229-7157-8f7a-a937-d9e1035af4c2
* Version Independent ID: 22ba54c4-069d-5c50-cade-edc27edd8581
* Content: [Set up a gMSAs for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain-gmsa#feedback)
* Content Source: [MIMDocs/preparing-domain-gmsa.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain-gmsa.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
