### ISSUE TITLE
Graph MA User Full Import Broken in 2/2020 release

### ISSUE THREAD

**Issue by Jason542** [MicrosoftDocs/MIMDocs#198]
User Full Import is broken in the Graph MA.  Syntax is wrong and appears to be a Delta Import so: Full User Import = Broken Delta Import.  Groups work OK, at least in a Full Import.

HttpStatusCode: BadRequest; 
url: https://graph.microsoft.com:443/v1.0/users/delta/?$deltaToken=latest&$select=country,userType,faxNumber,postalCode,employeeId,streetAddress,mailNickname,proxyAddresses,officeLocation,displayName,businessPhones,deviceEnrollmentLimit,city,id,jobTitle,companyName,surname,mobilePhone,mail,department,givenName,accountEnabled,manager; 
Response: {

    "message": "Invalid Request: $select is not supported for these properties.",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c4df6e-f886-e5b8-ae28-183def499df2
* Version Independent ID: 6ee14064-16b8-27e9-95ef-60fdec8f0da2
* Content: [Connector Version Release History](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/microsoft-identity-manager-2016-connector-version-history#feedback)
* Content Source: [MIMDocs/reference/microsoft-identity-manager-2016-connector-version-history.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/microsoft-identity-manager-2016-connector-version-history.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by EugeneSergeev** [comment]
thanks for your feedback, however, next time please use MIM2016@microsoft.com for the feedback as this feedback is supposed to be about documentation, not to troubleshoot issues.

as for your problem: not a connector issue. Try this request in Graph Explorer - you'll see that /delta/ query does not support deviceEnrollmentLimit attribute. Just remove it from your list.

**Comment by Jason542** [comment]
Ah, thanks – for some reason the attribute was checked by default after the MA install.


Jason Wagner

**Comment by markwahl-msft** [comment]
#please-close
