### ISSUE TITLE
Windows Server and SQL Server supported versions

### ISSUE THREAD

**Issue by celsoglima** [MicrosoftDocs/MIMDocs#201]
What are the specific reasons why MIM 2016 SP1 on Sharepoint 2016 is not supported on Server 2019? Server 2019 is a supported server version for Sharepoint 2016.  Would that be ok with the portal? Is there an issue with the MIM 2016 SP1 Sync service and Server 2019? What about SQL Server 2017? What makes it not a supported platform for MIM 2016 SP1? Could we run SQL Server 2016 SP2 on Windows Server 2019 which is a supported server version for that version of SQL server.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3fbb109-0afc-6a7b-2486-0d6412501d10
* Version Independent ID: 54e31b36-d865-79e6-0949-3fd9a2ce6978
* Content: [Supported software platforms](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-supported-platforms#feedback)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-supported-platforms.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-supported-platforms.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by markwahl-msft** [comment]
We typically introduce support for using MIM with new versions of dependencies or platform components in the next MIM service pack after that dependent software is generally available.  As customers should be upgrading to MIM 2016 SP2 we won't be retroactively adding support statements to previous MIM service packs.

**Comment by markwahl-msft** [comment]
#please-close
