### ISSUE TITLE
Add additional note for GMSA

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/MIMDocs#202]
Please add a note that you must check use a different account for exchange to use GMSA in the next screen.

If you do not you will receive the error The service account shouldn't be managed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 075343f5-fb83-36e7-2b3f-667aed1bda45
* Version Independent ID: a0962eb3-fa18-f808-818d-1d76c803045a
* Content: [Install Microsoft Identity Manager Service and Portal](https://docs.microsoft.com/en-us/microsoft-identity-manager/install-mim-service-portal)
* Content Source: [MIMDocs/install-mim-service-portal.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/install-mim-service-portal.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by EugeneSergeev** [comment]
already mentioned in step #7: "MIM 2016 SP2 and later: if you are using Group Managed Service Accounts, you must check Use different user for Exchange checkbox even if you do not plan to use Exchange."

**Comment by stephenc01** [comment]
not sure how I missed that one.
