### ISSUE TITLE
POST to endpoint does not return "application/json" valid data

### ISSUE THREAD

**Issue by rhblind** [MicrosoftDocs/MIMDocs#203]
Hello,
In the [HTTP request and response headers](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/certificate-management-rest-api-service-details#http-request-and-response-headers) document it says that the Content-Type for responses always are `application/json`. In the example response for [Create request](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/create-request) it says:

```
HTTP/1.1 201 Created

"api/v1.0/requests/a9b4b42c-cc50-4c9b-89d1-bbc0bcd5a099"
```

This response does not seems to conform with the `application/json` response Content-Type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84736382-405a-c478-703a-99ed5559eee1
* Version Independent ID: 002e681b-6d8c-f034-7ec1-9042b8bb54a3
* Content: [Create request](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/create-request)
* Content Source: [MIMDocs/reference/create-request.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/create-request.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
