### ISSUE TITLE
About groups used by MIM

### ISSUE THREAD

**Issue by kk-koji** [MicrosoftDocs/MIMDocs#204]
Please explain the permission groups required to run the synchronization script.
e.g. MIMSyncOperators group is needed to run the MA profiles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ab9211-b85c-9668-abcb-e5195a83ac43
* Version Independent ID: 649e1fd0-fc2c-4544-ee6b-45b2e67c26e5
* Content: [Install the Microsoft Identity Manager Sync Service](https://docs.microsoft.com/en-us/microsoft-identity-manager/install-mim-sync)
* Content Source: [MIMDocs/install-mim-sync.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/install-mim-sync.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
