### ISSUE TITLE
Sharepoint Farm

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/MIMDocs#205]
Please put an official statement on the support of the portal on a multi server SharePoint farm. Alot of man hours have been wasted for something that should be documented

Case: 120031924000197 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 075343f5-fb83-36e7-2b3f-667aed1bda45
* Version Independent ID: a0962eb3-fa18-f808-818d-1d76c803045a
* Content: [Install Microsoft Identity Manager Service and Portal](https://docs.microsoft.com/en-us/microsoft-identity-manager/install-mim-service-portal)
* Content Source: [MIMDocs/install-mim-service-portal.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/install-mim-service-portal.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by EugeneSergeev** [comment]
SP farms with multiple nodes are supported. 
However, every time you patch a farm node, it will cause WSP solution to be retracted and redeployed on all farm members, making them unusable; as WSP deployed won't match the binaries. 
So, the farm would be inaccessible until all nodes are patched. 2 nodes would cause WSP to be redeployed twice and in a not so fast environment this may cause timeouts and rollbacks, broken SP cache and such (unless an increased timeout value is specifiec).

as for the case number - work with CSS, documentation web site is not the right place for such discussions

**Comment by markwahl-msft** [comment]
#please-close
