### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by schmarrap** [MicrosoftDocs/MIMDocs#206]
for those that needed an easy copy and paste to enable diagnostic logging here is one that worked, the from the website doesn't. 

<source name="ConnectorsLog" switchValue="Verbose" switchType="System.Diagnostics.SourceSwitch">
    	   	<listeners>
        		<add initializeData="AZUREAD" type="System.Diagnostics.EventLogTraceListener" name="ConnectorsLogListener" 				

traceOutputOptions="LogicalOperationStack, DateTime, Timestamp, Callstack">
            		<filter type="" />
        	</add>
    		</listeners>
	</source>

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
