### ISSUE TITLE
PowerShell script doesn't create the "MIMInstall" required user account

### ISSUE THREAD

**Issue by CoadyTech** [MicrosoftDocs/MIMDocs#208]
The PowerShell script on this page don't create the required "MIMInstall" user which is referred to later in the guide. The first script block should be updated to include:

New-ADUser –SamAccountName MIMINSTALL –name MIMINSTALL
Set-ADAccountPassword –identity MIMINSTALL –NewPassword $sp
Set-ADUser –identity MIMINSTALL –Enabled 1 –PasswordNeverExpires 1

Then, the second script block should be updated to include:

Add-ADGroupmember -identity MIMSyncAdmins -Members MIMInstall

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b72229-7157-8f7a-a937-d9e1035af4c2
* Version Independent ID: 22ba54c4-069d-5c50-cade-edc27edd8581
* Content: [Set up a gMSAs for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain-gmsa#feedback)
* Content Source: [MIMDocs/preparing-domain-gmsa.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain-gmsa.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
