### ISSUE TITLE
Error in redirection

### ISSUE THREAD

**Issue by davidguest44** [MicrosoftDocs/MIMDocs#211]
The links to the Domino documentation - specifically around Setting up Notes users, User Registration, Managing users, Renaming users do not work as this documentation has been moved to HCL from IBM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22c24425-a22c-3292-4520-2aaf169836fd
* Version Independent ID: a5f723c1-a614-8f92-bea4-59bbf137c123
* Content: [Lotus Domino Connector](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/microsoft-identity-manager-2016-connector-domino?WT.mc_id=EM-MVP-5002871#feedback)
* Content Source: [MIMDocs/reference/microsoft-identity-manager-2016-connector-domino.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/microsoft-identity-manager-2016-connector-domino.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
