### ISSUE TITLE
Database Name Change Bug

### ISSUE THREAD

**Issue by SametKARA** [MicrosoftDocs/MIMDocs#214]
Hello there,

In a recent setup I changed the name of the database and got an error message. I noticed the problem when I examined the situation. The problem was caused by the [setup]. [EnableServiceBroker] stored procedure. 

The 'FIMService' name was coded in this SP. Although I made the name of the database 'MIMService', it was still trying to alter 'FIMService' database. What made me discover the problem was that there was a database named 'FIMService' and it was offline.

Is it possible to make a correction in this regard? because there may be situations where you need to change the name of the database.

You can find the post I explained in detail about my findings . But I published my post in Turkish :)
https://karasamet.wordpress.com/2020/05/08/mim-2016-service-and-portal-kurulumundaki-bug/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 075343f5-fb83-36e7-2b3f-667aed1bda45
* Version Independent ID: a0962eb3-fa18-f808-818d-1d76c803045a
* Content: [Install Microsoft Identity Manager Service and Portal](https://docs.microsoft.com/en-us/microsoft-identity-manager/install-mim-service-portal#feedback)
* Content Source: [MIMDocs/install-mim-service-portal.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/install-mim-service-portal.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by EugeneSergeev** [comment]
each MIM stored procedure has 'use <yourDBname>' statement generated by installer. so if you install SP2 from scratch and provide another DB name, e.g. myDB, this value will be found in all SPROCs.

it is not a supported flow to change your DB name and apply a hotfix on top of your existing installation because of this.

if you have a different flow - I would suggest to open a support case with CSS as this place is to discuss documentation bugs, not product behavior or misconfiguration

**Comment by SametKARA** [comment]
First of all, thank you for your reply. But I think there is a little misunderstanding. I apologize for my feedback is not understandable enough.

I wasn't trying to upgrade MIM. I was just trying to install "MIM 2016: MIM Service and Portal" in an environment where another "MIM 2016: MIM Service and Portal" installation has already been tried. Default database name("FIMService") was used but the customer does not want to continue with this setup. Therefore, firs installation was uninstalled and databases were switched to Offline mode. But that's just the story side of how I find this bug. 

Whether or not an installation has already been done does not change anything.If you want to see the bug, all you have to do is change the name of the database at the "MIM 2016: MIM Service and Portal" installation. Then if you look at the stored procedure named "[setup]. [EnableServiceBroker]", what you will see is that it has been created independently of the name you have given to the database.It will look exactly like below:

"SET NOCOUNT ON;

    

ALTER DATABASE [FIMService] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;

ALTER DATABASE [FIMService] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

ALTER DATABASE [FIMService] SET ENABLE_BROKER;

ALTER DATABASE [FIMService] SET MULTI_USER WITH ROLLBACK IMMEDIATE;

ALTER AUTHORIZATION ON DATABASE::[FIMService] TO [SA];"

**Comment by EugeneSergeev** [comment]
I do understand. not only this SP but other SPROCs have hardcoded DB name generated during the initial install process.
if you believe that installer should recreate all SPs - I would strongly suggest to open a case with CSS to get it fixed. this behavior hasn't changed since FIM RTM.

**Comment by markwahl-msft** [comment]
#please-close
