### ISSUE TITLE
16. On the server that will host MIM Service, MIM Service requires .NET Framework 3.5.

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/MIMDocs#216]
Microsoft MIM KeyProtectService as part of the sync service requires .net 3.5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9d25f8-acca-35b0-202b-f83a0a8c1e45
* Version Independent ID: bc769b6d-0c19-2590-a834-743620172fe9
* Content: [Configure Windows Server 2016 or 2019 for MIM 2016 SP2](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-ws2016)
* Content Source: [MIMDocs/prepare-server-ws2016.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-ws2016.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
