### ISSUE TITLE
Missing step

### ISSUE THREAD

**Issue by rviersel** [MicrosoftDocs/MIMDocs#218]
Step is missing at "Run the SharePoint Products Configuration Wizard to configure SharePoint", it should be noted that this should be run as "PRIV\Sharepoint", otherwise user will get the error "Cannot Connect To DataBase Master At SQL Server", even though this user with password has been provided in the wizard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5faf70f-a9fe-6fa8-9465-968550ee71a2
* Version Independent ID: 1599edaa-287f-c250-585c-14d67069613d
* Content: [Deploy PAM step 3 – PAM server](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/step-3-prepare-pam-server#feedback)
* Content Source: [MIMDocs/pam/step-3-prepare-pam-server.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/step-3-prepare-pam-server.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
