### ISSUE TITLE
MIM 2016 pre SP1 to SP2 upgrade clarification

### ISSUE THREAD

**Issue by darrenjrobinson** [MicrosoftDocs/MIMDocs#220]
This document states that 

> The minimal supported version of Forefront Identity Manager that can be directly upgraded to MIM 2016 SP2 is FIM 2010 R2 SP1 (build 4.1.3419.0). 

MIM SP2 states that the prerequisite is [Microsoft Identity Manager 2016 build 4.4.1302.0](https://support.microsoft.com/en-us/help/4512924/microsoft-identity-manager-2016-service-pack-2-build-4-6-34-0-update-r)

Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08e4586b-120f-cd84-2c51-d26d3d1681eb
* Version Independent ID: f86923f4-1e29-8197-940f-957b6d6ff5ea
* Content: [Upgrade from FIM 2010 R2 and MIM 2016 SP2 to Microsoft Identity Manager 2016 Service Pack 2](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-service-pack-2-upgrade-path#upgrade-from-previous-mim-2016-builds)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-service-pack-2-upgrade-path.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-service-pack-2-upgrade-path.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by EugeneSergeev** [comment]
The minimal supported version of Forefront Identity Manager that can be directly upgraded to MIM 2016 SP2 is FIM 2010 R2 SP1 (build 4.1.3419.0) - this information is correct.

**Comment by darrenjrobinson** [comment]
Thx Eugene. To confirm it is supported to
- upgrade from FIM 2010 R2 SP1 (build 4.1.3419.0 or later) to MIM 2016 SP2 (as per this document)
- upgrade from MIM 2016 (build 4.3.2064.0) to MIM 2016 SP2 an upgrade to build 4.4.1302.0 (SP1) is first required then to SP2 (as per the prerequisites in the SP1 & SP2 release notes)??

**Comment by EugeneSergeev** [comment]
you can do direct upgrade to MIM SP2 from 
a) FIM build 4.1.3419 and later
b) any public MIM build

**Comment by EugeneSergeev** [comment]
KB article updated. let's close this case

**Comment by darrenjrobinson** [comment]
Fantastic, thx Eugene. Much appreciated.

**Comment by EugeneSergeev** [comment]
not tested, therefore, not supported.
so, yes, 421 requires SP2 to be installed first.
