### ISSUE TITLE
Command to install required components is noit valid

### ISSUE THREAD

**Issue by PsCustomObject** [MicrosoftDocs/MIMDocs#222]
In step **7** of [Join Windows Server 2016 to your domain](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-ws2016#join-windows-server-2016-to-your-domain) we're instructed to run the following command from PowerShell

`
import-module ServerManager
Install-WindowsFeature Web-WebServer, Net-Framework-Features,rsat-ad-powershell,Web-Mgmt-Tools,Application-Server,Windows-Identity-Foundation,Server-Media-Foundation,Xps-Viewer –includeallsubfeature -restart -source d:\sources\SxS`

But this results in an error the the **Application-Server** role is not available in Windows 2016/2019.

Documentation should be updated to include the single components that should be installed in place of the Application-Role which has been deprecated since W2012 R2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9d25f8-acca-35b0-202b-f83a0a8c1e45
* Version Independent ID: bc769b6d-0c19-2590-a834-743620172fe9
* Content: [Configure Windows Server 2016 or 2019 for MIM 2016 SP2](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-ws2016)
* Content Source: [MIMDocs/prepare-server-ws2016.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-ws2016.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
