### ISSUE TITLE
Highest MIM Version for SharePoint 2016

### ISSUE THREAD

**Issue by stijh** [MicrosoftDocs/MIMDocs#224]
This doc seems to say that the highest version of the MIM Service and Portal that can be installed on a SharePoint 2016 farm is SP1 (which it looks like would be 4.5.412.0 according to https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/version-history but correct me if I am wrong) -- is this the case?

**Comment by markwahl-msft** [comment]
You should be able use MIM SP2 with a SharePoint farm, if a farm is necessary.
#please-close
