### ISSUE TITLE
date format mistake

### ISSUE THREAD

**Issue by guyhorn1964** [MicrosoftDocs/MIMDocs#226]
[Enter feedback here]
Hi. The date format should be "yyyy-MM-dd HH:mm.ss" You wrote "yyyy-MM-dd HH:MM.ss" which will give you month number back instead of minutes.

By the way. I have difficulties flowing the SignInActively.LastSignInDateTime. It causes a stopped-extensible-extension-error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08269662-0165-5225-6da2-33bbf9989f12
* Version Independent ID: d32b3f0b-2590-a119-0ee0-bbda1652904a
* Content: [Configuring the Microsoft Identity Manager connector for Microsoft Graph for B2B](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-graph-b2b-scenario)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-graph-b2b-scenario.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-graph-b2b-scenario.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
