### ISSUE TITLE
Error in miiserver.exe.config sample

### ISSUE THREAD

**Issue by lkline298** [MicrosoftDocs/MIMDocs#228]
"Call stack" should be one word, Callstack, not two as shown in the code sample.  Working Example:

<source name="ConnectorsLog" switchValue="Verbose" switchType="System.Diagnostics.SourceSwitch" >
	<listeners>
		<add initializeData="ConnectorsLog"
			type="System.Diagnostics.EventLogTraceListener, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
			name="ConnectorsLogListener" traceOutputOptions="LogicalOperationStack, DateTime, Timestamp, Callstack" />
		<remove name="Default" />
	</listeners>
</source>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa92c4b-1c4e-227b-4cbb-aafc579a0c71
* Version Independent ID: 8742167d-df6b-4424-0001-9c0fa1bd569c
* Content: [The Microsoft Identity Manager connector for Microsoft Graph](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-connector-graph)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-connector-graph.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-connector-graph.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @fimguy
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
