### ISSUE TITLE
Domain setup vs Domain setup for GMSA

### ISSUE THREAD

**Issue by schnitz76** [MicrosoftDocs/MIMDocs#232]
There needs to be more information about what steps need to be followed in this document vs Domain setup for GMSA when wanting to use GMSA.  Do I not follow this page at all when doing GMSA or do I still need certain accounts from this page to be created, but not others?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63b3e40-9767-a459-3c57-3aad83026b74
* Version Independent ID: d1cf0874-08cc-4c70-44d5-a1a625bdfe42
* Content: [Set up a domain for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain)
* Content Source: [MIMDocs/preparing-domain.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
