### ISSUE TITLE
Note section doesn't line up with the other pages.

### ISSUE THREAD

**Issue by schnitz76** [MicrosoftDocs/MIMDocs#233]
Information in the Note section does not match information in the Note section from any other page in this set of instructions.
This page:
 Note

This walkthrough uses sample names and values from a company called Contoso. Replace these with your own. For example:

Domain controller name - dc
Domain name - contoso
MIM Service Server name - mimservice
MIM Sync Server name - mimsync
SQL Server name - sql
Password - Pass@word1

All of the other pages:
Note

This walkthrough uses sample names and values from a company called Contoso. Replace these with your own. For example:

Domain controller name - corpdc
Domain name - contoso
MIM Service Server name - corpservice
MIM Sync Server name - corpsync
SQL Server name - corpsql
Password - Pass@word1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b72229-7157-8f7a-a937-d9e1035af4c2
* Version Independent ID: 22ba54c4-069d-5c50-cade-edc27edd8581
* Content: [Set up a gMSAs for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain-gmsa)
* Content Source: [MIMDocs/preparing-domain-gmsa.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain-gmsa.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
