### ISSUE TITLE
What GMSA accounts replace what regular domain accounts for the rest of the documentation? 

### ISSUE THREAD

**Issue by schnitz76** [MicrosoftDocs/MIMDocs#234]
Please add comments as to which GMSA accounts listed here replace what normal accounts in the "Domain setup" document.  Going through the rest of the documents I am left to guess when and where I replace the normal accounts with these GMSA accounts.  

Does MIMAdmin (GMSA) take the place of MIMInstall (nonGMSA)?
Does svcSharePoint (GMSA) take the place of SharePoint (nonGMSA)?
Does svcMIMSql (GMSA) take the place of SqlServer (nonGMSA)?
Does svcMIMAppPool (GMSA) take the place of MIMPool (nonGMSA)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b72229-7157-8f7a-a937-d9e1035af4c2
* Version Independent ID: 22ba54c4-069d-5c50-cade-edc27edd8581
* Content: [Set up a gMSAs for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain-gmsa)
* Content Source: [MIMDocs/preparing-domain-gmsa.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain-gmsa.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
