### ISSUE TITLE
Level 15 causes install to fail

### ISSUE THREAD

**Issue by schnitz76** [MicrosoftDocs/MIMDocs#236]
Note

Verify that the result of the CompatibilityLevel variable is “15”. If the result is other than “15”, then the site collection was not created the correct experience version; delete the site collection and recreate it.

When I made the Site Collection with level 15 MIM Service and Portal failed to install with and error about not upgrading the portal.  When I deleted the Site Collection and remade it with 14 and ran $site=Get-SPSite http://mim.contoso.com
$site.AllowSelfServiceUpgrade=$false it installed just fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bb5efc7-7c39-cf26-70ef-a324d215af76
* Version Independent ID: add2ba42-a910-ce5f-3767-35834085c2fa
* Content: [Configure SharePoint for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-sharepoint)
* Content Source: [MIMDocs/prepare-server-sharepoint.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-sharepoint.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
