### ISSUE TITLE
Version numbering correction

### ISSUE THREAD

**Issue by wbsteele1234** [MicrosoftDocs/MIMDocs#238]
Text below should read 4.4.1459.0
The 4 and 5 are reversed

Version 4.4.1549.0
Status: previous MIM 2016 SP1 Hotfix Update, of March 27, 2017
Corresponding BHOLD version number: 6.0.36.0
Read more at https://support.microsoft.com/en-us/help/4012498

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d8b69a-c572-fff1-6559-632ded8f9060
* Version Independent ID: 0cbcbb62-a0ee-de8f-8d1f-497a919d30ea
* Content: [Identity Manager version history](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/version-history)
* Content Source: [MIMDocs/reference/version-history.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/version-history.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
