### ISSUE TITLE
MIM Value Expression needs a LENGTH function.

### ISSUE THREAD

**Issue by tmunro55** [MicrosoftDocs/MIMDocs#239]
[Enter feedback here]

The basic data retrieval functions offered for Value Expressions in MIM (not MIMWAL) needs a LENGTH function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ffb09f-fb6a-7cd5-0ad4-3ee74e2b8065
* Version Independent ID: 93b25d6d-fee4-98f4-83e6-a08b47932c85
* Content: [Functions reference for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/mim2016-functions-reference)
* Content Source: [MIMDocs/reference/mim2016-functions-reference.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/mim2016-functions-reference.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
