### ISSUE TITLE
Typo in MIM Versions page

### ISSUE THREAD

**Issue by JBWCowling** [MicrosoftDocs/MIMDocs#240]
Hi, There is a typo here:

Version 4.5.202.0
<snip>
Visual C++ 2013 x64 Redistributable Packages (vcresist_x64.exe) is required

vcresist should be vcredist

Not tragic, but thought I'd mention it... Great page, use it all the time...

Cheers

James

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d8b69a-c572-fff1-6559-632ded8f9060
* Version Independent ID: 0cbcbb62-a0ee-de8f-8d1f-497a919d30ea
* Content: [Identity Manager version history](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/version-history)
* Content Source: [MIMDocs/reference/version-history.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/version-history.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
