### ISSUE TITLE
Why are we creating normal accounts on the gMSA page

### ISSUE THREAD

**Issue by WillyMoselhy** [MicrosoftDocs/MIMDocs#241]
Do we need to create svcSharePoint, and svcSharePoint if we are going to use gMSA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b72229-7157-8f7a-a937-d9e1035af4c2
* Version Independent ID: 22ba54c4-069d-5c50-cade-edc27edd8581
* Content: [Set up a gMSAs for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/preparing-domain-gmsa)
* Content Source: [MIMDocs/preparing-domain-gmsa.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/preparing-domain-gmsa.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by EugeneSergeev** [comment]
SharePoint does not support GMSA

**Comment by markwahl-msft** [comment]
#please-close
