### ISSUE TITLE
Application Server Deprecated

### ISSUE THREAD

**Issue by jlinesnm** [MicrosoftDocs/MIMDocs#244]
Step 6 says to Add Web Server (IIS) and Application Server. Application server cannot be added due to it being deprecated in Server 2016. The page offers no other info for installing Application Server. It doesn’t even tell you that it’s been deprecated, and the PowerShell script in Step 7 includes Application Server which makes it impossible to use. I had to search the internet and finally found a good script that contained all the necessary components:

Add-WindowsFeature Web-Server, windows-identity-foundation, Net-Framework-45-ASPNET, Net-Framework-Features, Web-Mgmt-Console, Web-Mgmt-Compat, Web-Metabase, Web-Lgcy-Mgmt-Console, Web-Lgcy-Scripting, Web-Mgmt-Tools, Web-WMI, Web-Common-HTTP. Web-Windows-Auth, NET-HTTP-Activation, NET-Non-HTTP-Activ, NET-WCF-HTTP-Activation45, rsat-ad-powershell, Server-Media-Foundation, Xps-Viewer -includeallsubfeature -source F:\sources\sxs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9d25f8-acca-35b0-202b-f83a0a8c1e45
* Version Independent ID: bc769b6d-0c19-2590-a834-743620172fe9
* Content: [Configure Windows Server 2016 or 2019 for MIM 2016 SP2](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-ws2016)
* Content Source: [MIMDocs/prepare-server-ws2016.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-ws2016.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by mliben** [comment]
Good tip. Note there are a couple of periods that should be commas in the command line so may want to double check before executing.
