### ISSUE TITLE
Word works not as described. 

### ISSUE THREAD

**Issue by guyhorn1964** [MicrosoftDocs/MIMDocs#247]
[Enter feedback here]
The Word function is not described correctly. If I use it like this (//wfd/AccountName Word([//WorkflowData/UserPrincipalName],0,"@") > MailNickname) and the userPrincioanName is guy.horn@hotmail.com then I get back guy.horn. Accordint to the description Ill get an empty string. Thats wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ffb09f-fb6a-7cd5-0ad4-3ee74e2b8065
* Version Independent ID: 93b25d6d-fee4-98f4-83e6-a08b47932c85
* Content: [Functions reference for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/mim2016-functions-reference)
* Content Source: [MIMDocs/reference/mim2016-functions-reference.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/mim2016-functions-reference.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
