### ISSUE TITLE
Users Access rights information missing

### ISSUE THREAD

**Issue by akg322** [MicrosoftDocs/MIMDocs#253]
[Enter feedback here]
As a beginner I tried to install MIM following the doc. and It failed as MIMINSTALL user needs access rights on SQL server, but in the doc it is not mentioned what exact rights to be given for each user that were created for installation,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ab9211-b85c-9668-abcb-e5195a83ac43
* Version Independent ID: 649e1fd0-fc2c-4544-ee6b-45b2e67c26e5
* Content: [Install the Microsoft Identity Manager Sync Service](https://docs.microsoft.com/en-us/microsoft-identity-manager/install-mim-sync)
* Content Source: [MIMDocs/install-mim-sync.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/install-mim-sync.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by PLA-Chris** [comment]
Agreed. You are asked to perform the install as Administrator who has no access to the SQL DB. You need to add a login and appropriate roles for the Administrator account (or add MIMAdmin to DA group and use that. Additionally Adminsitrator is missing from the Collections Permission in SharePoint.

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
