### ISSUE TITLE
Titles in menu and pages does not match

### ISSUE THREAD

**Issue by sivisal** [MicrosoftDocs/MIMDocs#254]
The left hand menu has "step 6" title as "Create privileged accounts", but when clicking it, the title is "Transition a group to Privileged Access Management" and the page title is "Move group". I'm pretty sure that step 6 actually describe "create privileged accounts".

Other steps here have similar problems, where the title does not match between the left hand menu, the page title and what is written on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9667ac18-588a-670b-2c91-b3cd9fc10376
* Version Independent ID: 31d9509a-8e31-477a-dc2a-b84b27eb6f46
* Content: [Deploy PAM step 6 – Move group](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/step-6-transition-group-to-pam)
* Content Source: [MIMDocs/pam/step-6-transition-group-to-pam.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/step-6-transition-group-to-pam.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close

**Comment by New-Authentication** [comment]
Still an issue but whatever...
