### ISSUE TITLE
Azure Multi-Factor Authentication Server not available for new deployments

### ISSUE THREAD

**Issue by martin-rublik** [MicrosoftDocs/MIMDocs#255]
Hi 

since Azure MFA Server is not available for new deployments (https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfaserver-deploy) what is the current integration option for Azure MFA and MIM SSPR?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de6da5e0-b92d-fe6f-6052-294b6b9b6254
* Version Independent ID: 237cd9aa-1ea8-3f2c-9b06-c071adc519de
* Content: [Use Azure Multi-Factor Authentication Server to activate PAM or SSPR Scenarios](https://docs.microsoft.com/en-us/microsoft-identity-manager/working-with-mfaserver-for-mim)
* Content Source: [MIMDocs/working-with-mfaserver-for-mim.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/working-with-mfaserver-for-mim.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by markwahl-msft** [comment]
If you need to use MFA during SSPR, we would recommend using the Azure AD SSPR reset experience instead.  See `https://docs.microsoft.com/azure/active-directory/authentication/howto-sspr-authenticationdata` for how to register a use for Azure AD SSPR.

**Comment by markwahl-msft** [comment]
#please-close
