### ISSUE TITLE
Need To Call out Full Text Search Requirement

### ISSUE THREAD

**Issue by mliben** [MicrosoftDocs/MIMDocs#256]
Handed the instructions off to a client's dba and they performed their own canned install instead of using the suggested command line. It was not immediately obvious to them that the Full Text Search option was required as it is not documented anywhere on the page.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35c89d56-ac27-c024-d0d4-1d9c3608bf33
* Version Independent ID: ab422d09-d7c1-e068-dfce-d4cdcfbcb3b9
* Content: [Configure SQL Server for Microsoft Identity Manager 2016 SP2](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-sql2016?source=docs)
* Content Source: [MIMDocs/prepare-server-sql2016.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-sql2016.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
