### ISSUE TITLE
Link to comparison article

### ISSUE THREAD

**Issue by Bob-Bradley** [MicrosoftDocs/MIMDocs#257]
I believe this page would be improved by linking to [Hybrid Identity directory integration tools comparison](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/plan-hybrid-identity-design-considerations-tools-comparison) when referring to ongoing Microsoft support for MIM Synchronisation.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 720992cd-e2bc-d993-ef47-70205afe92ee
* Version Independent ID: ea9a8093-2861-0dc3-0c78-f11b1c944579
* Content: [Support update for Azure AD Premium customers using Microsoft Identity Manager](https://docs.microsoft.com/en-us/microsoft-identity-manager/support-update-for-azure-active-directory-premium-customers)
* Content Source: [MIMDocs/support-update-for-azure-active-directory-premium-customers.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/support-update-for-azure-active-directory-premium-customers.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
