### ISSUE TITLE
Need instructions attached/referenced to explain how to use prerequisite installer in an Air Gap environment. (No Internet AccessO

### ISSUE THREAD

**Issue by dkhill** [MicrosoftDocs/MIMDocs#258]
It would be most beneficial to have instruction linked to this page that explains how to perform the SharePoint prerequisite installation in a Air Gapped environment.  I.e.

I had to search around several forums, YouTube videos etc. to come up with a process to perform the prerequisite installer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bb5efc7-7c39-cf26-70ef-a324d215af76
* Version Independent ID: add2ba42-a910-ce5f-3767-35834085c2fa
* Content: [Configure SharePoint for Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-sharepoint)
* Content Source: [MIMDocs/prepare-server-sharepoint.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-sharepoint.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
