### ISSUE TITLE
IIS Section of the document is incomplete

### ISSUE THREAD

**Issue by lsousa-code** [MicrosoftDocs/MIMDocs#260]
[Enter feedback here]

The IIS section has issues. 
The Powershell in the IIS Section misses the configuration  file path an the configuration file is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8708773-cc27-2e60-9609-4ca90de5d1ac
* Version Independent ID: 613f0ad5-a1a2-cb73-4b9b-e3a4537cd80d
* Content: [Deploying Microsoft Identity Manager Certificate Manager](https://docs.microsoft.com/en-us/microsoft-identity-manager/mim-cm-deploy)
* Content Source: [MIMDocs/mim-cm-deploy.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/mim-cm-deploy.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lfasousa77** [comment]
The Features need for IIS are described here.
https://docs.microsoft.com/en-us/previous-versions/mim/gg418619(v=ws.10)

Can help to fix the article?
lsousa@microsoft.com 
Thanks

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
