### ISSUE TITLE
Upgrade 4.3.2064.0 to 4.6.421.0

### ISSUE THREAD

**Issue by darrenjrobinson** [MicrosoftDocs/MIMDocs#261]
[Release notes for 4.6.421.0](https://support.microsoft.com/en-us/topic/microsoft-identity-manager-2016-build-4-6-421-0-update-rollup-is-available-bdf9d5af-6e6f-a588-c585-5bcca5bddf9b) indicate that MIM 2016 Service Pack 2 (SP2) build 4.6.34.0  is required as the minimum for the 4.6.421.0 rollup.
I have another environment that needs to be updated to the most recent release. Would like to do it in one update process as per this previous clarification https://github.com/MicrosoftDocs/MIMDocs/issues/220 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d8b69a-c572-fff1-6559-632ded8f9060
* Version Independent ID: 0cbcbb62-a0ee-de8f-8d1f-497a919d30ea
* Content: [Identity Manager version history](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/version-history?form=MY01SV&OCID=MY01SV#mim-version-464210)
* Content Source: [MIMDocs/reference/version-history.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/version-history.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
