### ISSUE TITLE
The first view is wrong. 

### ISSUE THREAD

**Issue by guyhorn1964** [MicrosoftDocs/MIMDocs#262]
The first view of the "Multitier topology" is wrong. The fimservice is not connected to HR server, The fimsynchronizationservice does that using a management agent. 

I dont expect money but a good word on my LinkedIn page would be great. search for https://www.linkedin.com/in/horn-iamexpert/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2625af9-8587-9e56-c965-f823e6d3f3e9
* Version Independent ID: 3479cc4e-90d1-65a9-e44a-de4e46f675f7
* Content: [Topology guide for deployment](https://docs.microsoft.com/en-us/microsoft-identity-manager/topology-considerations)
* Content Source: [MIMDocs/topology-considerations.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/topology-considerations.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by kenilelk** [comment]
>I dont expect money but a good word on my LinkedIn page would be great.
search for https://www.linkedin.com/in/horn-iamexpert/
>On Fri, 6 Aug 2021, 15:05 guyhorn1964, ***@***.***> wrote

Really?

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
