### ISSUE TITLE
What does mean Active Directory version here?

### ISSUE THREAD

**Issue by amdf777** [MicrosoftDocs/MIMDocs#264]
Here is the quote:
<html>
<body>

Active Directory for user provisioning, PCNS, and GAL Sync (optional) | Windows Server 2012Windows Server 2012 R2Windows Server 2016 *Windows Server 2019 **
-- | --

</body>
</html>

Is this Domain Controller version or what?
DFL and FFL I can find above this. Thus AD version here confusing. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3fbb109-0afc-6a7b-2486-0d6412501d10
* Version Independent ID: 54e31b36-d865-79e6-0949-3fd9a2ce6978
* Content: [Supported software platforms](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-supported-platforms)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-supported-platforms.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-supported-platforms.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
