### ISSUE TITLE
Oracle Internet Directory not supported but fixes in the changelog?

### ISSUE THREAD

**Issue by sanderdewit** [MicrosoftDocs/MIMDocs#265]
Hello,

I was looking into the integration with the Oracle Internet Directory with the generic LDAP connector.
It's listed as being not supported, however at the same time I noticed in the connector changelog;

"Generic LDAP Connector
Delta import no longer fails if Changes field is empty in Oracle Internet Directory"
https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/microsoft-identity-manager-2016-connector-version-history

If this support statement still valid?
What are the reasons this is not supported, as it seems to be in line with the generic ldap v3 connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c50515-fbee-e2b3-4fe0-b598b2b0042a
* Version Independent ID: d43540e7-e7a2-6f3f-23f2-607c60fe90dc
* Content: [Generic LDAP Connector](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/microsoft-identity-manager-2016-connector-genericldap)
* Content Source: [MIMDocs/reference/microsoft-identity-manager-2016-connector-genericldap.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/reference/microsoft-identity-manager-2016-connector-genericldap.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
