### ISSUE TITLE
The query filters section  

### ISSUE THREAD

**Issue by oknyazev** [MicrosoftDocs/MIMDocs#267]
The query filters section dialog screenshot contains filter StartWith, it supposed to be StartsWith
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa92c4b-1c4e-227b-4cbb-aafc579a0c71
* Version Independent ID: 8742167d-df6b-4424-0001-9c0fa1bd569c
* Content: [The Microsoft Identity Manager connector for Microsoft Graph](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-connector-graph)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-connector-graph.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-connector-graph.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by EugeneSergeev** [comment]
@oknyazev fixed. thanks.

**Comment by markwahl-msft** [comment]
#please-close
