### ISSUE TITLE
Server setup instructions are out of date for Server 2016+

### ISSUE THREAD

**Issue by pluto00987** [MicrosoftDocs/MIMDocs#270]
This page says to install the 'Application Server' role in steps 6 and 7, but that role is no longer available in Server 2016 or later. It's not clear what roles/features are actually needed on those OSs.

Also, steps 6 and 7 are redundant: They accomplish the same thing by two different methods. It could be noted to do one or the other as appropriate.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9d25f8-acca-35b0-202b-f83a0a8c1e45
* Version Independent ID: bc769b6d-0c19-2590-a834-743620172fe9
* Content: [Configure Windows Server 2016 or 2019 for MIM 2016 SP2](https://docs.microsoft.com/en-us/microsoft-identity-manager/prepare-server-ws2016)
* Content Source: [MIMDocs/prepare-server-ws2016.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-ws2016.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
