### ISSUE TITLE
Broken LInk

### ISSUE THREAD

**Issue by ms-mjkatz** [MicrosoftDocs/MIMDocs#271]
[Enter feedback here]
This link is broken, https://aka.ms/MIMforAADP   It goes to a Surface page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea2a5249-61f8-bc0d-82bc-d2b5d1e11b79
* Version Independent ID: 79f5a969-4bcd-ceba-7770-7069f723d8bf
* Content: [Microsoft Identity Manager](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016)
* Content Source: [MIMDocs/microsoft-identity-manager-2016.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by EugeneSergeev** [comment]
link is not broken and points to https://www.microsoft.com/en-us/download/details.aspx?id=102887
