### ISSUE TITLE
Incorrect value in the Relationship criteria (step 6)

### ISSUE THREAD

**Issue by sylvainclb** [MicrosoftDocs/MIMDocs#273]
The Step 6: Create the synchronization rule have an incorrect value in the Relationship criteria.
The ILM Attribute is "Data Source Attribute". It should be "accountName".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7d8ad1e-df34-629f-e05d-0a7683b2f1eb
* Version Independent ID: 3c1a9981-7c98-49d1-ba85-5292bbabd7c2
* Content: [Microsoft Identity Manager 2016 user provisioning to AD](https://docs.microsoft.com/en-us/microsoft-identity-manager/mim-how-provision-users-adds)
* Content Source: [MIMDocs/mim-how-provision-users-adds.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/mim-how-provision-users-adds.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
