### ISSUE TITLE
quote: 'Verify that the user can authenticate to the REST API.....'     WHICH USER???

### ISSUE THREAD

**Issue by RobMulder** [MicrosoftDocs/MIMDocs#278]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1bca92a8-7f5a-6917-326e-626715e3165e
* Version Independent ID: a4562e7d-7cd7-b529-119d-9a14629f2a85
* Content: [Deploy PAM step 4 – Install MIM](https://learn.microsoft.com/en-us/microsoft-identity-manager/pam/step-4-install-mim-components-on-pam-server)
* Content Source: [MIMDocs/pam/step-4-install-mim-components-on-pam-server.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/step-4-install-mim-components-on-pam-server.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
