### ISSUE TITLE
AD requirements for connection destination

### ISSUE THREAD

**Issue by KJ2256** [MicrosoftDocs/MIMDocs#280]
[Enter feedback here]
When provisioning AD with MIM, is FSMO recommended for the target AD?
It is impractical to build the MIM on-premise, for example, when the AD of the on-premise DC is FSMO and the MIM is Azure, etc.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2625af9-8587-9e56-c965-f823e6d3f3e9
* Version Independent ID: 3479cc4e-90d1-65a9-e44a-de4e46f675f7
* Content: [Topology guide for deployment](https://learn.microsoft.com/en-us/microsoft-identity-manager/topology-considerations)
* Content Source: [MIMDocs/topology-considerations.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/topology-considerations.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
