### ISSUE TITLE
Features to be installed are different than listed in the article

### ISSUE THREAD

**Issue by josuvil** [MicrosoftDocs/MIMDocs#282]
Hello,

During installation of Service and Portal using MIM 2016 SP2, the default features listed are different than what is explained: 

![image](https://user-images.githubusercontent.com/28968872/214323839-dff4831f-b4a6-48c4-a4d0-e471bcea3a98.png)

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 075343f5-fb83-36e7-2b3f-667aed1bda45
* Version Independent ID: a0962eb3-fa18-f808-818d-1d76c803045a
* Content: [Install Microsoft Identity Manager Service and Portal](https://learn.microsoft.com/en-us/microsoft-identity-manager/install-mim-service-portal?source=docs)
* Content Source: [MIMDocs/install-mim-service-portal.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/install-mim-service-portal.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
