### ISSUE TITLE
"PIM" incorrectly used instead of "PAM"

### ISSUE THREAD

**Issue by jaymichaud** [MicrosoftDocs/MIMDocs#285]
Under the heading, "How does MIM PAM work?" (h2 element id="how-does-mim-pam-work"), the third paragraph incorrectly uses the abbreviation "PIM" instead of "PAM". Please correct this as follows:

- Current text (incorrect): The following example shows how PIM works in more detail.
- Replacement text (correct): The following example shows how PAM works in more detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f97232d5-629b-3ac3-7b67-4af90e70c551
* Version Independent ID: e2c1c9d6-8b91-5dee-3240-668e4c3158a4
* Content: [Privileged Access Management for Active Directory Domain Services](https://learn.microsoft.com/en-us/microsoft-identity-manager/pam/privileged-identity-management-for-active-directory-domain-services)
* Content Source: [MIMDocs/pam/privileged-identity-management-for-active-directory-domain-services.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/privileged-identity-management-for-active-directory-domain-services.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
