### ISSUE TITLE
Disable SharePoint indexing instructions outdated

### ISSUE THREAD

**Issue by aydeisen** [MicrosoftDocs/MIMDocs#286]
In the section to [Disable SharePoint indexing](https://learn.microsoft.com/en-us/microsoft-identity-manager/mim-best-practices#disable-sharepoint-indexing) the instructions don't line up with the portal experience.

- SharePoint Central Administration is not located under Administrative Tools
- There is no Operations link or page
- There is no "Global Configuration" or Timer job definitions

What are the correct steps supposed to be for MIM 2016 when its underlying SharePoint system is SharePoint Server 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4c298cb-2abb-6ede-c062-41a744b698c0
* Version Independent ID: 132d1643-dd10-d034-421a-2281b940c3ea
* Content: [Microsoft Identity Manager 2016 Best Practices](https://learn.microsoft.com/en-us/microsoft-identity-manager/mim-best-practices)
* Content Source: [MIMDocs/mim-best-practices.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/mim-best-practices.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
