### ISSUE TITLE
Suggested PowerShell Script is broken due to missing or misnamed Windows Feature

### ISSUE THREAD

**Issue by johnekare-advania** [MicrosoftDocs/MIMDocs#292]
Hello! At step seven (7) of the guide to prepare a Windows Server 2016 (or later) for Microsoft Identity Manager, the PowerShell script provided references a Windows Feature by the name of "Application-Server". When Running the script it outputs the following error message (in the example it is one of many features, but here I have isolated the specific feature, since it was the only one failing to install):

Install-WindowsFeature : ArgumentNotValid: The role, role service, or feature name is not valid: 'Application-Server'. The name was not found.
At line:1 char:1
+ Install-WindowsFeature Application-Server –IncludeAllSubFeature -Rest ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Application-Server:String) [Install-WindowsFeature], Exception
    + FullyQualifiedErrorId : NameDoesNotExist,Microsoft.Windows.ServerManager.Commands.AddWindowsFeatureCommand

I am running the script on a Windows Server 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba9d25f8-acca-35b0-202b-f83a0a8c1e45
* Version Independent ID: bc769b6d-0c19-2590-a834-743620172fe9
* Content: [Configure Windows Server 2016 or later versions for MIM 2016 SP2](https://learn.microsoft.com/en-us/microsoft-identity-manager/prepare-server-ws2016)
* Content Source: [MIMDocs/prepare-server-ws2016.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-ws2016.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
