### ISSUE TITLE
Example code missing referenced DLL(s)

### ISSUE THREAD

**Issue by MXHancock** [MicrosoftDocs/MIMDocs#294]
The example code provided uses "Microsoft.IdentityManagement.PhoneServiceProvider" but it does not include which DLL needs to referenced to get this to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c119cf2-34be-b124-c0fa-755adcad7f4b
* Version Independent ID: 38e64dab-4233-dbad-3cb5-8445496572b6
* Content: [Use an MFA provider via an API to activate PAM or in SSPR scenario](https://learn.microsoft.com/en-us/microsoft-identity-manager/working-with-custommfaserver-for-mim)
* Content Source: [MIMDocs/working-with-custommfaserver-for-mim.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/working-with-custommfaserver-for-mim.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
