### ISSUE TITLE
Incorrect hotfix linked

### ISSUE THREAD

**Issue by Niehweune** [MicrosoftDocs/MIMDocs#297]
Prerequisites listed for the Graph MA have this:

Microsoft Identity Manager 2016 SP2, and must use hotfix 4.4.1642.0 [KB4021562](https://www.microsoft.com/en-us/download/details.aspx?id=55794) or later.

However, the hotfix referred to doesn't apply to MIM 2016 SP2

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: caa92c4b-1c4e-227b-4cbb-aafc579a0c71
* Version Independent ID: 8742167d-df6b-4424-0001-9c0fa1bd569c
* Content: [The Microsoft Identity Manager connector for Microsoft Graph](https://learn.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016-connector-graph)
* Content Source: [MIMDocs/microsoft-identity-manager-2016-connector-graph.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-2016-connector-graph.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @EugeneSergeev
* Microsoft Alias: **esergeev**

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
