### ISSUE TITLE
fix powershell command to install 'Application-Server' role

### ISSUE THREAD

**Issue by KoenigTH** [MicrosoftDocs/MIMDocs#299]
Hi there, under point 7 in the section "Join Windows Server 2016 to your domain" the installation command ist faulty. 
You can't install the 'Application-Server' role anymore. 

Please fix that in the documentation.

best regards
Thorsten

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba9d25f8-acca-35b0-202b-f83a0a8c1e45
* Version Independent ID: bc769b6d-0c19-2590-a834-743620172fe9
* Content: [Configure Windows Server 2016 or later versions for MIM 2016 SP2](https://learn.microsoft.com/en-us/microsoft-identity-manager/prepare-server-ws2016)
* Content Source: [MIMDocs/prepare-server-ws2016.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/prepare-server-ws2016.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
