### ISSUE TITLE
references to contoso.local

### ISSUE THREAD

**Issue by clknerr** [MicrosoftDocs/MIMDocs#85]
.local is a dns suffix that is used for Multicast DNS traffic and should not be used for a domain name in Active Directory. References to contoso.local should be updated to reference something in line with Microsoft's own guidance in regards to domain naming, such as "*.ad.contoso.com".

Please see guidance from Microsoft here: 
https://technet.microsoft.com/en-us/library/cc726016

Specifically:
"Do not use single-label DNS names. For more information, see Information about configuring Windows for domains with single-label DNS names (http://go.microsoft.com/fwlink/?LinkId=106631). Also, we do not recommend using unregistered suffixes, such as .local."

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
