### ISSUE TITLE
This install process is wrong

### ISSUE THREAD

**Issue by k3llybush** [MicrosoftDocs/MIMDocs#98]
NO WAY with this install guide can you get this setup to work.  The authors need to revisit this and correct it.  I've tried countless times to get this to work and it just doesn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8073c156-16d9-4f1f-8317-d04f5a557c2a
* Version Independent ID: 5be71c21-a3af-fee7-a314-ffa67165c392
* Content: [Steps required to deploy Microsoft Identity Manager 2016](https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-deploy)
* Content Source: [MIMDocs/microsoft-identity-manager-deploy.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/microsoft-identity-manager-deploy.md)
* Service: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **barclayn**

**Comment by billmath** [comment]
@k3llybush thank you for submitting this.  I have created a work item for this and will be adding this to my monthly sprints.  We can go ahead and close this issue for now and I will re-open it and post a response once this is complete.  Also, I sent you an email with some workarounds that might help until this is validated.  Let me know if you have any questions on those.  Thank you!

**Comment by billmath** [comment]
#please-close

**Comment by billmath** [comment]
#please-close

**Comment by markwahl-msft** [comment]
#please-close
